In [1]:
import polars as pl
from ergochemics.standardize import standardize_smiles
from functools import partial
from ergochemics.draw import draw_molecule

In [84]:
std_smi = partial(standardize_smiles, neutralization_method="simple", quiet=True)

In [85]:
name_smi = {}
with open("/home/stef/bottle/artifacts/4228703247252781668.txt", "r") as f:
    for line in f.readlines():
        split_line = line.strip().split("\t")
        if len(split_line) == 2:
            name, smi = split_line
            name_smi[name] = std_smi(smi)

In [86]:
beachheads = [
    "D-Xylose",
    "Protocatechuic acid",
    "Pyruvate",
    "Malonyl-CoA",
    "L-aspartate",
    "Citrate",
    "Geranyl diphosphate",
    "Geranylgeranyl diphosphate",
    "Farnesyl diphosphate",
    "L-glutamate",
]

potential_beachheads = [
    "Glycerol",
    "L-Tyrosine",
    "Prephenic acid",
    "Chorismate",
    "Acetolactate",
    "2-Ketoisovalerate",
    "Acetoacetyl-CoA",
    "Acetyl-CoA",
    "2-Ketobutyric acid",
    "Propionyl-CoA",
    "L-lysine",
    "Glutaric acid",
    "Succinyl-CoA",
    "L-Proline",
    "L-Arginine",
]

targets = [
    "cis,cis-Muconic acid",
    "3-Hydroxypropionic acid",
    "cis-Aconitate",
    "Cineole",
    "Bisabolene",
    "Kaurene"
]

In [87]:
missing_smiles = []
for group_name, group in zip(["beachheads", "potential_beachheads", "targets"], [beachheads, potential_beachheads, targets]):
    for name in group:
        missing_smiles.append(name) if name not in name_smi else None

In [88]:
missing_smiles

[]

In [89]:
with open("round_2.txt", "w") as f:
    for name in missing_smiles:
        f.write(f"{name}\n")

In [90]:
table = []
for name, smi in name_smi.items():
    table.append(
        [name, smi, name in beachheads, name in potential_beachheads, name in targets]
    )   
    
df = pl.DataFrame(
    table,
    schema=[
        ("name", pl.String),
        ("smiles", pl.String),
        ("beachhead", pl.Boolean),
        ("potential_beachhead", pl.Boolean),
        ("target", pl.Boolean),
    ]
)
df.head()

/tmp/ipykernel_175240/18072210.py:7: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  df = pl.DataFrame(

shape: (5, 5)
┌──────────────────────┬──────────────────────┬───────────┬─────────────────────┬────────┐
│ name                 ┆ smiles               ┆ beachhead ┆ potential_beachhead ┆ target │
│ ---                  ┆ ---                  ┆ ---       ┆ ---                 ┆ ---    │
│ str                  ┆ str                  ┆ bool      ┆ bool                ┆ bool   │
╞══════════════════════╪══════════════════════╪═══════════╪═════════════════════╪════════╡
│ Glucose              ┆ OCC1OC(O)C(O)C(O)C1O ┆ false     ┆ false               ┆ false  │
│ Pyruvate             ┆ CC(=O)C(=O)O         ┆ true      ┆ false               ┆ false  │
│ D-xylono-1,4-lactone ┆ O=C1OC(CO)C(O)C1O    ┆ false     ┆ false               ┆ false  │
│ 4-Hydroxyhexan-3-one ┆ CCC(=O)C(O)CC        ┆ false     ┆ false               ┆ false  │
│ Propanal             ┆ CCC=O                ┆ false     ┆ false               ┆ false  │
└──────────────────────┴──────────────────────┴───────────┴─────────────────────┴────────┘

In [91]:
df.write_csv(
    "/home/stef/bottle/artifacts/agile_biofoundry.tsv",
    separator="\t",
)

In [2]:
am_rxns = pl.read_parquet("/home/stef/quest_data/bottle/data/interim/expansions/5_steps_combo_mechinferred_dt_13_and_mechinferred_dt_04_rules/am_rxns.parquet")

In [4]:
len(am_rxns), len(am_rxns.unique("am_smarts"))

(413044, 413044)

In [6]:
from src.network import de_am
from ergochemics.standardize import hash_reaction

In [5]:
am_rxns.head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────┐
│ am_smarts                       ┆ rules                       │
│ ---                             ┆ ---                         │
│ str                             ┆ list[str]                   │
╞═════════════════════════════════╪═════════════════════════════╡
│ [NH2:14][C:15](=[O:16])[C:17]1… ┆ ["mechinferred_dt_04:6572"] │
│ [NH2:102][C:103](=[O:104])[C:1… ┆ ["mechinferred_dt_04:1754"] │
│ [O:1]=[C:2]([OH:3])[CH2:4][CH2… ┆ ["mechinferred_dt_13:7"]    │
│ [CH3:1][C:2]([CH3:3])([CH2:4][… ┆ ["mechinferred_dt_04:1757"] │
│ [CH3:1][O:2][CH:3]([CH:4]1[CH2… ┆ ["mechinferred_dt_04:5975"] │
└─────────────────────────────────┴─────────────────────────────┘

In [7]:
am_rxns = am_rxns.with_columns(
    pl.col("am_smarts").map_elements(de_am).alias("am_smarts")
)

/tmp/ipykernel_938818/4110477149.py:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  am_rxns = am_rxns.with_columns(

In [11]:
am_rxns.head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────┐
│ am_smarts                       ┆ rules                       │
│ ---                             ┆ ---                         │
│ list[list[str]]                 ┆ list[str]                   │
╞═════════════════════════════════╪═════════════════════════════╡
│ [["NC(=O)C1=CN(C2OC(COP(=O)(O)… ┆ ["mechinferred_dt_04:6572"] │
│ [["NC(=O)C1=CN(C2OC(COP(=O)(O)… ┆ ["mechinferred_dt_04:1754"] │
│ [["O=C(O)CCC(=O)OO", "NC(=O)C1… ┆ ["mechinferred_dt_13:7"]    │
│ [["CC(C)(COP(=O)(O)OP(=O)(O)OC… ┆ ["mechinferred_dt_04:1757"] │
│ [["COC(C1CO1)C(O)C(O)C(O)O"], … ┆ ["mechinferred_dt_04:5975"] │
└─────────────────────────────────┴─────────────────────────────┘

In [12]:
from minedatabase.pickaxe import Pickaxe

In [13]:
pk = Pickaxe()
pk.load_pickled_pickaxe(

    "/home/stef/quest_data/bottle/results/raw_expansions/2_steps_ccm_aa_to_None_rules_mechinferred_dt_13_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_True.pk"
)

----------------------------------------
Intializing pickaxe object

Done intializing pickaxe object
----------------------------------------

Loading /home/stef/quest_data/bottle/results/raw_expansions/2_steps_ccm_aa_to_None_rules_mechinferred_dt_13_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_True.pk pickled data.
Loaded 61480 compounds
Loaded 138825 reactions
Loaded 7635 operators
Loaded 70 coreactants
Loaded 2 generation
Took 2.207806348800659

[16:07:40] WARNING: not removing hydrogen atom without neighbors

In [14]:
pk.operators

{'0_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57740>,
  {'Name': '0_0',
   'Reactants': ['Any', 'WATER'],
   'SMARTS': '[C&D2&v4&H0&+0&!R&z2:1]#[N&D1&v3&H0&+0&!R:2].[O&D0&v2&H2&+0&!R:3]>>[C&D3&v4&H0&+0&!R&z3:1](-[N&D1&v3&H2&+0&!R:2])=[O&D1&v2&H0&+0&!R:3]',
   'Products': ['Any'],
   '_id': '0_0',
   'Reactions_predicted': 0}),
 '1_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57790>,
  {'Name': '1_0',
   'Reactants': ['Any', 'WATER'],
   'SMARTS': '[C&D2&v4&H0&+0&!R&z2:1]#[N&D1&v3&H0&+0&!R:2].[O&D0&v2&H2&+0&!R:3]>>[C&D2&v4&H1&+0&!R&z2:1]=[N&D2&v3&H0&+0&!R:2]-[O&D1&v2&H1&+0&!R:3]',
   'Products': ['Any'],
   '_id': '1_0',
   'Reactions_predicted': 0}),
 '2_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd577e0>,
  {'Name': '2_0_1',
   'Reactants': ['O2', 'CYSTEINE_COREACTANT', 'CYSTEINE_COREACTANT'],
   'SMARTS': '[O&D1&v2&H0&+0&!R:1]=[O&D1&v2&H0&+0&!R:2].[S&D1&v2&H1&+0&!R:3].[S&D1&v2&H1&+0&!R:4]>>[O&D1&v2&H1&+0&!R:1]-[O&D1&v2&H1&+0&!R:2].[S&D2&v2&H0&+0&!R:3]-[S&D2&v2&H0&+0&!R:4]',
   'Products': ['H2O2', 'Any'],
   '_id': '2_0_1',
   'Reactions_predicted': 0}),
 '3_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57830>,
  {'Name': '3_0',
   'Reactants': ['H2O2', 'Any'],
   'SMARTS': '[O&D1&v2&H1&+0&!R:1]-[O&D1&v2&H1&+0&!R:2].[S&D2&v2&H0&+0&!R:3]-[S&D2&v2&H0&+0&!R:4]>>[O&D1&v2&H0&+0&!R:1]=[O&D1&v2&H0&+0&!R:2].[S&D1&v2&H1&+0&!R:3].[S&D1&v2&H1&+0&!R:4]',
   'Products': ['O2', 'Any', 'Any'],
   '_id': '3_0',
   'Reactions_predicted': 0}),
 '4_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57880>,
  {'Name': '4_0',
   'Reactants': ['Any'],
   'SMARTS': '([C&D3&v4&H0&+0&!R&z1:1](=[C&D2&v4&H1&+0&!R&z0:2])~[*:3]~[O&D1&v2&H0&+0&!R:4].[O&D1&v2&H1&+0&!R:5])>>[C&D3&v4&H1&+0&R&z1:2](-[O&D2&v2&H0&+0&R:5])-[C&D3&v4&H1&+0&R&z1:1]~[*:3]~[O&D1&v2&H0&+0&!R:4]',
   'Products': ['Any'],
   '_id': '4_0',
   'Reactions_predicted': 0}),
 '5_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd578d0>,
  {'Name': '5_0',
   'Reactants': ['Any', 'H2O2'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1]=[N&D1&v3&H1&+0&!R:2].[O&D1&v2&H1&+0&!R:3]-[O&D1&v2&H1&+0&!R:4]>>[C&D3&v4&H1&+0&!R&z2:1]-[N&D1&v3&H2&+0&!R:2].[O&D1&v2&H0&+0&!R:3]=[O&D1&v2&H0&+0&!R:4]',
   'Products': ['Any', 'O2'],
   '_id': '5_0',
   'Reactions_predicted': 0}),
 '6_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57920>,
  {'Name': '6_0',
   'Reactants': ['Any', 'WATER'],
   'SMARTS': '[*:1](~[N&D2&v3&H0&+0&!R:2])~[S&D2&v2&H0&+0&!R:3]-[C&D3&v4&H1&+0&R&z2:4](-[O&D2&v2&H0&+0&R:5])-[C&D3&v4&H1&+0&R&z1:6]-[O&D1&v2&H1&+0&!R:7].[O&D0&v2&H2&+0&!R:8]>>[*:1](~[S&D1&v2&H1&+0&!R:3])~[N&D2&v3&H0&+0&!R:2].[O&D2&v2&H0&+0&R:5]-[C&D3&v4&H1&+0&R&z2:4](-[O&D1&v2&H1&+0&!R:8])-[C&D3&v4&H1&+0&R&z1:6]-[O&D1&v2&H1&+0&!R:7]',
   'Products': ['Any', 'Any'],
   '_id': '6_0',
   'Reactions_predicted': 0}),
 '7_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57970>,
  {'Name': '7_0_0',
   'Reactants': ['SUCCINATE_COREACTANT', 'Any'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1]=[O&D1&v2&H0&+0&!R:2].[C&D3&v4&H0&+0&R&z0:3]1=[C&D2&v4&H1&+0&R&z1:4]-[N&D3&v3&H0&+0&R:5](-[C&D3&v4&H1&+0&R&z2:6]-[C&D3&v4&H1&+0&R&z1:7]-[O&D1&v2&H1&+0&!R:8])-[C&D2&v4&H1&+0&R&z1:9]=[C&D2&v4&H1&+0&R&z0:10]-[C&D2&v4&H2&+0&R&z0:11]-1>>[C&D3&v4&H1&+0&!R&z2:1]-[O&D1&v2&H1&+0&!R:2].[c&D3&v4&H0&+0&R&z0:3]1:[c&D2&v4&H1&+0&R&z0:11]:[c&D2&v4&H1&+0&R&z0:10]:[c&D2&v4&H1&+0&R&z1:9]:[n&D3&v4&H0&+&R:5](-[C&D3&v4&H1&+0&R&z2:6]-[C&D3&v4&H1&+0&R&z1:7]-[O&D1&v2&H1&+0&!R:8]):[c&D2&v4&H1&+0&R&z1:4]:1',
   'Products': ['Any', 'Any'],
   '_id': '7_0_0',
   'Reactions_predicted': 0}),
 '7_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd579c0>,
  {'Name': '7_1',
   'Reactants': ['Any', 'NADH_CoF'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1]=[O&D1&v2&H0&+0&!R:2].[C&D3&v4&H0&+0&R&z0:3]1=[C&D2&v4&H1&+0&R&z1:4]-[N&D3&v3&H0&+0&R:5](-[C&D3&v4&H1&+0&R&z2:6]-[C&D3&v4&H1&+0&R&z1:7]-[O&D1&v2&H1&+0&!R:8])-[C&D2&v4&H1&+0&R&z1:9]=[C&D2&v4&H1&+0&R&z0:10]-[C&D2&v4&H2&+0&R&z0:11]-1>>[C&D3&v4&H1&+0&!R&z2:1]-[O&D1&v2&H1&+0&!R:2].[c&D3&v4&H0&+0&R&z0:3]1:[c&D2&v4&H1&+0&R&z0:11]:[c&D2&v4&H1&+0&R&z0:10]:[c&D2&v4&H1&+0&R&z1:9]:[n&D3&v4&H0&+&R:5](-[C&D3&v4&H1&+0&R&z2:6]-[C&D3&v4&H1&+0&R&z1:7]-[O&D1&v2&H1&+0&!R:8]):[c&D2&v4&H1&+0&R&z1:4]:1',
   'Products': ['Any', 'NAD_CoF'],
   '_id': '7_1',
   'Reactions_predicted': 0}),
 '8_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57a10>,
  {'Name': '8_0',
   'Reactants': ['Any', 'ACETYL-COA'],
   'SMARTS': '[N&D1&v3&H2&+0&!R:1].[N&D2&v3&H1&+0&!R:2]-[C&D3&v4&H0&+0&!R&z2:3]=[O&D1&v2&H0&+0&!R:4]>>[N&D1&v3&H2&+0&!R:2].[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:3]=[O&D1&v2&H0&+0&!R:4]',
   'Products': ['Any', 'CoA'],
   '_id': '8_0',
   'Reactions_predicted': 0}),
 '8_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57a60>,
  {'Name': '8_1_0',
   'Reactants': ['ALANINE_COREACTANT', 'Any'],
   'SMARTS': '[N&D1&v3&H2&+0&!R:1].[N&D2&v3&H1&+0&!R:2]-[C&D3&v4&H0&+0&!R&z2:3]=[O&D1&v2&H0&+0&!R:4]>>[N&D1&v3&H2&+0&!R:2].[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:3]=[O&D1&v2&H0&+0&!R:4]',
   'Products': ['Any', 'Any'],
   '_id': '8_1_0',
   'Reactions_predicted': 0}),
 '8_2': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57ab0>,
  {'Name': '8_2',
   'Reactants': ['Any', 'CoA'],
   'SMARTS': '[N&D1&v3&H2&+0&!R:1].[N&D2&v3&H1&+0&!R:2]-[C&D3&v4&H0&+0&!R&z2:3]=[O&D1&v2&H0&+0&!R:4]>>[N&D1&v3&H2&+0&!R:2].[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:3]=[O&D1&v2&H0&+0&!R:4]',
   'Products': ['Any', 'ACETYL-COA'],
   '_id': '8_2',
   'Reactions_predicted': 0}),
 '1258_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57b00>,
  {'Name': '1258_0_0',
   'Reactants': ['Any', 'ALANINE_COREACTANT'],
   'SMARTS': '[*:1](~[O&D1&v2&H1&+0&!R:2])~[*:3]~[O&D2&v2&H0&+0&!R:4]-[C&D3&v4&H0&+0&!R&z2:5](=[O&D1&v2&H0&+0&!R:6])-[C&D3&v4&H1&+0&!R&z1:7].[N&D1&v3&H2&+0&!R:8]>>[*:1](~[O&D1&v2&H1&+0&!R:2])~[*:3]~[O&D1&v2&H1&+0&!R:4].[N&D2&v3&H1&+0&!R:8]-[C&D3&v4&H0&+0&!R&z2:5](=[O&D1&v2&H0&+0&!R:6])-[C&D3&v4&H1&+0&!R&z1:7]',
   'Products': ['Any', 'Any'],
   '_id': '1258_0_0',
   'Reactions_predicted': 0}),
 '10_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57b50>,
  {'Name': '10_0',
   'Reactants': ['ACETYL-COA', 'Any'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])-[S&D2&v2&H0&+0&!R:3].[N&D1&v3&H2&+0&!R:4]>>[N&D2&v3&H1&+0&!R:4]-[C&D3&v4&H0&+0&!R&z2:1]=[O&D1&v2&H0&+0&!R:2].[S&D1&v2&H1&+0&!R:3]',
   'Products': ['Any', 'CoA'],
   '_id': '10_0',
   'Reactions_predicted': 0}),
 '10_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57ba0>,
  {'Name': '10_1_0',
   'Reactants': ['Any', 'ALANINE_COREACTANT'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])-[S&D2&v2&H0&+0&!R:3].[N&D1&v3&H2&+0&!R:4]>>[N&D2&v3&H1&+0&!R:4]-[C&D3&v4&H0&+0&!R&z2:1]=[O&D1&v2&H0&+0&!R:2].[S&D1&v2&H1&+0&!R:3]',
   'Products': ['Any', 'Any'],
   '_id': '10_1_0',
   'Reactions_predicted': 0}),
 '10_2': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57bf0>,
  {'Name': '10_2_0',
   'Reactants': ['Any', 'ALANINE_COREACTANT'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])-[S&D2&v2&H0&+0&!R:3].[N&D1&v3&H2&+0&!R:4]>>[N&D2&v3&H1&+0&!R:4]-[C&D3&v4&H0&+0&!R&z2:1]=[O&D1&v2&H0&+0&!R:2].[S&D1&v2&H1&+0&!R:3]',
   'Products': ['Any', 'CoA'],
   '_id': '10_2_0',
   'Reactions_predicted': 0}),
 '11_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57c40>,
  {'Name': '11_0_1',
   'Reactants': ['ALANINE_COREACTANT', 'ALANINE_COREACTANT'],
   'SMARTS': '[C&D3&v4&H1&+0&!R&z1:1](-[N&D1&v3&H2&+0&!R:2])-[C&D3&v4&H0&+0&!R&z2:3](=[O&D1&v2&H0&+0&!R:4])-[O&D1&v2&H1&+0&!R:5].[N&D1&v3&H2&+0&!R:6]>>[N&D2&v3&H1&+0&!R:6]-[C&D3&v4&H0&+0&!R&z2:3](=[O&D1&v2&H0&+0&!R:4])-[C&D3&v4&H1&+0&!R&z1:1]-[N&D1&v3&H2&+0&!R:2].[O&D0&v2&H2&+0&!R:5]',
   'Products': ['Any', 'WATER'],
   '_id': '11_0_1',
   'Reactions_predicted': 0}),
 '13_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57c90>,
  {'Name': '13_0_0',
   'Reactants': ['Any', 'CYSTEINE_COREACTANT'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:2]=[O&D1&v2&H0&+0&!R:3].[S&D1&v2&H1&+0&!R:4]>>[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[S&D2&v2&H0&+0&!R:4].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '13_0_0',
   'Reactions_predicted': 0}),
 '13_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57ce0>,
  {'Name': '13_1',
   'Reactants': ['Any', 'CoA'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:2]=[O&D1&v2&H0&+0&!R:3].[S&D1&v2&H1&+0&!R:4]>>[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[S&D2&v2&H0&+0&!R:4].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['ACETYL-COA', 'Any'],
   '_id': '13_1',
   'Reactions_predicted': 0}),
 '13_2': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57d30>,
  {'Name': '13_2',
   'Reactants': ['Any', 'CoA'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:2]=[O&D1&v2&H0&+0&!R:3].[S&D1&v2&H1&+0&!R:4]>>[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[S&D2&v2&H0&+0&!R:4].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '13_2',
   'Reactions_predicted': 0}),
 '1245_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57d80>,
  {'Name': '1245_0',
   'Reactants': ['Any', 'Any'],
   'SMARTS': '[*:1](~[O&D1&v2&H1&+0&!R:2])~[C&D3&v4&H1&+0&R&z1:3]-[O&D1&v2&H1&+0&!R:4].[N&D2&v3&H1&+0&!R:5]-[C&D3&v4&H0&+0&!R&z2:6](=[O&D1&v2&H0&+0&!R:7])-[C&D3&v4&H1&+0&!R&z1:8]>>[*:1](~[O&D1&v2&H1&+0&!R:2])~[C&D3&v4&H1&+0&R&z1:3]-[O&D2&v2&H0&+0&!R:4]-[C&D3&v4&H0&+0&!R&z2:6](=[O&D1&v2&H0&+0&!R:7])-[C&D3&v4&H1&+0&!R&z1:8].[N&D1&v3&H2&+0&!R:5]',
   'Products': ['Any', 'Any'],
   '_id': '1245_0',
   'Reactions_predicted': 0}),
 '15_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57dd0>,
  {'Name': '15_0',
   'Reactants': ['Any', 'WATER'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[C&D3&v4&H1&+0&!R&z1:4]-[N&D1&v3&H2&+0&!R:5].[O&D0&v2&H2&+0&!R:6]>>[C&D3&v4&H1&+0&!R&z1:4](-[N&D1&v3&H2&+0&!R:5])-[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[O&D1&v2&H1&+0&!R:6].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '15_0',
   'Reactions_predicted': 0}),
 '17_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57e20>,
  {'Name': '17_0_0',
   'Reactants': ['Any', 'ALANINE_COREACTANT'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])~[*:3](~[O&D1&v2&H0&+0&!R:4])~[O&D1&v2&H1&+0&!R:5].[C&D3&v4&H1&+0&!R&z1:6](-[N&D1&v3&H2&+0&!R:7])-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10]>>[C&D3&v4&H0&+0&!R&z1:6](=[O&D1&v2&H0&+0&!R:2])-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10].[C&D3&v4&H1&+0&!R&z2:1](-[N&D1&v3&H2&+0&!R:7])~[*:3](~[O&D1&v2&H0&+0&!R:4])~[O&D1&v2&H1&+0&!R:5]',
   'Products': ['Any', 'Any'],
   '_id': '17_0_0',
   'Reactions_predicted': 0}),
 '17_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57e70>,
  {'Name': '17_1',
   'Reactants': ['CARBONYL_CoF', 'AMINO_CoF'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])~[*:3](~[O&D1&v2&H0&+0&!R:4])~[O&D1&v2&H1&+0&!R:5].[C&D3&v4&H1&+0&!R&z1:6](-[N&D1&v3&H2&+0&!R:7])-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10]>>[C&D3&v4&H0&+0&!R&z1:6](=[O&D1&v2&H0&+0&!R:2])-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10].[C&D3&v4&H1&+0&!R&z2:1](-[N&D1&v3&H2&+0&!R:7])~[*:3](~[O&D1&v2&H0&+0&!R:4])~[O&D1&v2&H1&+0&!R:5]',
   'Products': ['CARBONYL_CoF', 'AMINO_CoF'],
   '_id': '17_1',
   'Reactions_predicted': 0}),
 '19_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57ec0>,
  {'Name': '19_0_0',
   'Reactants': ['Any', 'GLYCINE_COREACTANT'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])-[C&D3&v4&H0&+0&!R&z2:3](=[O&D1&v2&H0&+0&!R:4])-[O&D1&v2&H1&+0&!R:5].[N&D1&v3&H2&+0&!R:6]-[C&D2&v4&H2&+0&!R&z1:7]-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10]>>[C&D3&v4&H1&+0&!R&z2:1](-[N&D1&v3&H2&+0&!R:6])-[C&D3&v4&H0&+0&!R&z2:3](=[O&D1&v2&H0&+0&!R:4])-[O&D1&v2&H1&+0&!R:5].[O&D1&v2&H0&+0&!R:2]=[C&D2&v4&H1&+0&!R&z1:7]-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10]',
   'Products': ['Any', 'Any'],
   '_id': '19_0_0',
   'Reactions_predicted': 0}),
 '19_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57f10>,
  {'Name': '19_1',
   'Reactants': ['CARBONYL_CoF', 'AMINO_CoF'],
   'SMARTS': '[C&D3&v4&H0&+0&!R&z2:1](=[O&D1&v2&H0&+0&!R:2])-[C&D3&v4&H0&+0&!R&z2:3](=[O&D1&v2&H0&+0&!R:4])-[O&D1&v2&H1&+0&!R:5].[N&D1&v3&H2&+0&!R:6]-[C&D2&v4&H2&+0&!R&z1:7]-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10]>>[C&D3&v4&H1&+0&!R&z2:1](-[N&D1&v3&H2&+0&!R:6])-[C&D3&v4&H0&+0&!R&z2:3](=[O&D1&v2&H0&+0&!R:4])-[O&D1&v2&H1&+0&!R:5].[O&D1&v2&H0&+0&!R:2]=[C&D2&v4&H1&+0&!R&z1:7]-[C&D3&v4&H0&+0&!R&z2:8](=[O&D1&v2&H0&+0&!R:9])-[O&D1&v2&H1&+0&!R:10]',
   'Products': ['AMINO_CoF', 'CARBONYL_CoF'],
   '_id': '19_1',
   'Reactions_predicted': 0}),
 '20_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57f60>,
  {'Name': '20_0_1',
   'Reactants': ['Any', 'METHIONINE_COREACTANT', 'METHIONINE_COREACTANT'],
   'SMARTS': '[N&D3&v3&H0&+0&!R:1](-[C&D1&v4&H3&+0&!R&z1:2])-[C&D1&v4&H3&+0&!R&z1:3].[S&D2&v2&H0&+0&!R:4].[S&D2&v2&H0&+0&!R:5]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:4].[C&D1&v4&H3&+0&!R&z1:3]-[S&D3&v3&H0&+&!R:5].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['Any', 'Any', 'Any'],
   '_id': '20_0_1',
   'Reactions_predicted': 0}),
 '20_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dedd57fb0>,
  {'Name': '20_1',
   'Reactants': ['Any', 'METHYL_ACCEPTOR_CoF', 'METHYL_ACCEPTOR_CoF'],
   'SMARTS': '[N&D3&v3&H0&+0&!R:1](-[C&D1&v4&H3&+0&!R&z1:2])-[C&D1&v4&H3&+0&!R&z1:3].[S&D2&v2&H0&+0&!R:4].[S&D2&v2&H0&+0&!R:5]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:4].[C&D1&v4&H3&+0&!R&z1:3]-[S&D3&v3&H0&+&!R:5].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['METHYL_DONOR_CoF', 'METHYL_DONOR_CoF', 'Any'],
   '_id': '20_1',
   'Reactions_predicted': 0}),
 '21_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0040>,
  {'Name': '21_0_0',
   'Reactants': ['Any', 'Any', 'ALANINE_COREACTANT'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[C&D1&v4&H3&+0&!R&z1:3]-[S&D3&v3&H0&+&!R:4].[N&D1&v3&H2&+0&!R:5]>>[N&D3&v3&H0&+0&!R:5](-[C&D1&v4&H3&+0&!R&z1:1])-[C&D1&v4&H3&+0&!R&z1:3].[S&D2&v2&H0&+0&!R:2].[S&D2&v2&H0&+0&!R:4]',
   'Products': ['Any', 'Any', 'Any'],
   '_id': '21_0_0',
   'Reactions_predicted': 0}),
 '21_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0090>,
  {'Name': '21_1',
   'Reactants': ['METHYL_DONOR_CoF', 'METHYL_DONOR_CoF', 'Any'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[C&D1&v4&H3&+0&!R&z1:3]-[S&D3&v3&H0&+&!R:4].[N&D1&v3&H2&+0&!R:5]>>[N&D3&v3&H0&+0&!R:5](-[C&D1&v4&H3&+0&!R&z1:1])-[C&D1&v4&H3&+0&!R&z1:3].[S&D2&v2&H0&+0&!R:2].[S&D2&v2&H0&+0&!R:4]',
   'Products': ['Any', 'METHYL_ACCEPTOR_CoF', 'METHYL_ACCEPTOR_CoF'],
   '_id': '21_1',
   'Reactions_predicted': 0}),
 '23_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757e04609670>,
  {'Name': '23_0',
   'Reactants': ['Any', 'WATER'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[C&D3&v4&H1&+0&!R&z1:4].[O&D0&v2&H2&+0&!R:5]>>[C&D3&v4&H1&+0&!R&z1:4]-[C&D3&v4&H0&+0&!R&z2:2](=[O&D1&v2&H0&+0&!R:3])-[O&D1&v2&H1&+0&!R:5].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '23_0',
   'Reactions_predicted': 0}),
 '24_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b00e0>,
  {'Name': '24_0',
   'Reactants': ['Any', 'Any'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[N&D3&v3&H0&+0&!R:3]>>[N&D4&v4&H0&+&!R:3]-[C&D1&v4&H3&+0&!R&z1:1].[S&D2&v2&H0&+0&!R:2]',
   'Products': ['Any', 'Any'],
   '_id': '24_0',
   'Reactions_predicted': 0}),
 '24_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0130>,
  {'Name': '24_1',
   'Reactants': ['METHYL_DONOR_CoF', 'Any'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[N&D3&v3&H0&+0&!R:3]>>[N&D4&v4&H0&+&!R:3]-[C&D1&v4&H3&+0&!R&z1:1].[S&D2&v2&H0&+0&!R:2]',
   'Products': ['Any', 'METHYL_ACCEPTOR_CoF'],
   '_id': '24_1',
   'Reactions_predicted': 0}),
 '25_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0180>,
  {'Name': '25_0_0',
   'Reactants': ['Any', 'METHIONINE_COREACTANT'],
   'SMARTS': '[N&D3&v3&H0&+0&!R:1]-[C&D1&v4&H3&+0&!R&z1:2].[S&D2&v2&H0&+0&!R:3]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:3].[N&D2&v3&H1&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '25_0_0',
   'Reactions_predicted': 0}),
 '25_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757e07ae0360>,
  {'Name': '25_1',
   'Reactants': ['Any', 'METHYL_ACCEPTOR_CoF'],
   'SMARTS': '[N&D3&v3&H0&+0&!R:1]-[C&D1&v4&H3&+0&!R&z1:2].[S&D2&v2&H0&+0&!R:3]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:3].[N&D2&v3&H1&+0&!R:1]',
   'Products': ['METHYL_DONOR_CoF', 'Any'],
   '_id': '25_1',
   'Reactions_predicted': 0}),
 '26_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b01d0>,
  {'Name': '26_0_0',
   'Reactants': ['Any', 'ALANINE_COREACTANT'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[N&D1&v3&H2&+0&!R:3]>>[N&D2&v3&H1&+0&!R:3]-[C&D1&v4&H3&+0&!R&z1:1].[S&D2&v2&H0&+0&!R:2]',
   'Products': ['Any', 'Any'],
   '_id': '26_0_0',
   'Reactions_predicted': 0}),
 '26_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0220>,
  {'Name': '26_1',
   'Reactants': ['METHYL_DONOR_CoF', 'Any'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[N&D1&v3&H2&+0&!R:3]>>[N&D2&v3&H1&+0&!R:3]-[C&D1&v4&H3&+0&!R&z1:1].[S&D2&v2&H0&+0&!R:2]',
   'Products': ['Any', 'METHYL_ACCEPTOR_CoF'],
   '_id': '26_1',
   'Reactions_predicted': 0}),
 '27_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0270>,
  {'Name': '27_0',
   'Reactants': ['Any', 'Any'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[N&D2&v3&H1&+0&!R:3]>>[N&D3&v3&H0&+0&!R:3]-[C&D1&v4&H3&+0&!R&z1:1].[S&D2&v2&H0&+0&!R:2]',
   'Products': ['Any', 'Any'],
   '_id': '27_0',
   'Reactions_predicted': 0}),
 '27_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b02c0>,
  {'Name': '27_1',
   'Reactants': ['METHYL_DONOR_CoF', 'Any'],
   'SMARTS': '[C&D1&v4&H3&+0&!R&z1:1]-[S&D3&v3&H0&+&!R:2].[N&D2&v3&H1&+0&!R:3]>>[N&D3&v3&H0&+0&!R:3]-[C&D1&v4&H3&+0&!R&z1:1].[S&D2&v2&H0&+0&!R:2]',
   'Products': ['Any', 'METHYL_ACCEPTOR_CoF'],
   '_id': '27_1',
   'Reactions_predicted': 0}),
 '28_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0310>,
  {'Name': '28_0_0',
   'Reactants': ['Any', 'METHIONINE_COREACTANT'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D1&v4&H3&+0&!R&z1:2].[S&D2&v2&H0&+0&!R:3]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:3].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '28_0_0',
   'Reactions_predicted': 0}),
 '28_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0360>,
  {'Name': '28_1',
   'Reactants': ['Any', 'METHYL_ACCEPTOR_CoF'],
   'SMARTS': '[N&D2&v3&H1&+0&!R:1]-[C&D1&v4&H3&+0&!R&z1:2].[S&D2&v2&H0&+0&!R:3]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:3].[N&D1&v3&H2&+0&!R:1]',
   'Products': ['METHYL_DONOR_CoF', 'Any'],
   '_id': '28_1',
   'Reactions_predicted': 0}),
 '29_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757e04664590>,
  {'Name': '29_0_0',
   'Reactants': ['Any', 'METHIONINE_COREACTANT'],
   'SMARTS': '[N&D4&v4&H0&+&!R:1]-[C&D1&v4&H3&+0&!R&z1:2].[S&D2&v2&H0&+0&!R:3]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:3].[N&D3&v3&H0&+0&!R:1]',
   'Products': ['Any', 'Any'],
   '_id': '29_0_0',
   'Reactions_predicted': 0}),
 '29_1': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b03b0>,
  {'Name': '29_1',
   'Reactants': ['Any', 'METHYL_ACCEPTOR_CoF'],
   'SMARTS': '[N&D4&v4&H0&+&!R:1]-[C&D1&v4&H3&+0&!R&z1:2].[S&D2&v2&H0&+0&!R:3]>>[C&D1&v4&H3&+0&!R&z1:2]-[S&D3&v3&H0&+&!R:3].[N&D3&v3&H0&+0&!R:1]',
   'Products': ['METHYL_DONOR_CoF', 'Any'],
   '_id': '29_1',
   'Reactions_predicted': 0}),
 '30_0': (<rdkit.Chem.rdChemReactions.ChemicalReaction at 0x757dec2b0400>,
  {'Name': '30_0_0',

In [15]:
from rdkit import Chem
from rdkit.Chem import AllChem

In [17]:
rxn = AllChem.ReactionFromSmarts(pk.operators['0_0'][1]['SMARTS'])

In [20]:
for rct in rxn.GetReactants():
    print(rct.GetNumAtoms())

2
1

In [21]:
mapped = pl.read_parquet("/home/stef/bottle/artifacts/rxn_x_rule_mapping/mapped_known_reactions_x_mechinferred_dt_91_rules.parquet")
mapped.head()

shape: (5, 6)
┌─────────────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┬─────────┐
│ rxn_id          ┆ smarts          ┆ am_smarts       ┆ rule            ┆ template_aidxs ┆ rule_id │
│ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---            ┆ ---     │
│ str             ┆ str             ┆ str             ┆ str             ┆ str            ┆ i64     │
╞═════════════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╪═════════╡
│ 4fc554b86bb6450 ┆ *C#N.O>>*C(N)=O ┆ [*:4][C:1]#[N:2 ┆ [C&D2&v4&H0&+0& ┆ 1,2;0>>1,2,3   ┆ 0       │
│ 4ce3bb78f4c02ac ┆                 ┆ ].[OH2:3]>>[*:4 ┆ !R&z2:1]#[N&D1& ┆                ┆         │
│ …               ┆                 ┆ …               ┆ …               ┆                ┆         │
│ 4fe435c487c7b2d ┆ *C#N.O>>*C=NO   ┆ [*:4][C:1]#[N:2 ┆ [C&D2&v4&H0&+0& ┆ 1,2;0>>1,2,3   ┆ 1       │
│ c720dff02a9af2d ┆                 ┆ ].[OH2:3]>>[*:4 ┆ !R&z2:1]#[N&D1& ┆                ┆         │
│ …               ┆                 ┆ …               ┆ …               ┆                ┆         │
│ db3a4d53e3f2557 ┆ O=O.*C(*)S.*C(* ┆ [O:1]=[O:2].[*: ┆ [O&D1&v2&H0&+0& ┆ 0,1;3;3>>0,1;3 ┆ 2       │
│ babac4615ca5518 ┆ )S>>OO.*C(*)SSC ┆ 6][CH:5]([*:7]) ┆ !R:1]=[O&D1&v2& ┆ ,4             ┆         │
│ …               ┆ …               ┆ …               ┆ …               ┆                ┆         │
│ 74aa76da460568c ┆ OO.*C(*)SSC(*)* ┆ [OH:1][OH:2].[* ┆ [O&D1&v2&H1&+0& ┆ 0,1;3,4>>0,1;3 ┆ 3       │
│ cddd08f17f78cd8 ┆ >>O=O.*C(*)S.*C ┆ :5][CH:4]([*:6] ┆ !R:1]-[O&D1&v2& ┆ ;3             ┆         │
│ …               ┆ …               ┆ …               ┆ …               ┆                ┆         │
│ 40c96410b09d3b0 ┆ *C(=Cc1c(*)c(*) ┆ [*:4][C:3](=[CH ┆ ([C&D3&v4&H0&+0 ┆ 1,2,26>>7,8,21 ┆ 4       │
│ ef8fb9420f28029 ┆ c(*)c(*)c1*)C(= ┆ :1][c:17]1[c:18 ┆ &!R&z1:1]=[C&D2 ┆                ┆         │
│ …               ┆ …               ┆ …               ┆ …               ┆                ┆         │
└─────────────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┴─────────┘

In [26]:
import polars as pl

df_example = pl.DataFrame({
    "key": ["A", "B", "A", "C", "B", "A"],
    "value": [1, 2, 3, 4, 5, 3],
    "other": ["foo", "bar", "baz", "qux", "quux", "corge"]
})

df_example

shape: (6, 3)
┌─────┬───────┬───────┐
│ key ┆ value ┆ other │
│ --- ┆ ---   ┆ ---   │
│ str ┆ i64   ┆ str   │
╞═════╪═══════╪═══════╡
│ A   ┆ 1     ┆ foo   │
│ B   ┆ 2     ┆ bar   │
│ A   ┆ 3     ┆ baz   │
│ C   ┆ 4     ┆ qux   │
│ B   ┆ 5     ┆ quux  │
│ A   ┆ 3     ┆ corge │
└─────┴───────┴───────┘

In [27]:
df_example_max = df_example.sort("value", descending=True).unique(subset=["key"])
df_example_max

shape: (3, 3)
┌─────┬───────┬───────┐
│ key ┆ value ┆ other │
│ --- ┆ ---   ┆ ---   │
│ str ┆ i64   ┆ str   │
╞═════╪═══════╪═══════╡
│ A   ┆ 3     ┆ baz   │
│ C   ┆ 4     ┆ qux   │
│ B   ┆ 5     ┆ quux  │
└─────┴───────┴───────┘