In [1]:
import pandas as pd

In [2]:
path = '/projects/b1039/spn1560/bottle/data/interim/expansions/3_steps_bottle_targets_25_to_None_rules_mechinferred_dt_04_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_False/compounds.parquet'

In [3]:
df = pd.read_parquet(path)
df.head()

,id,smiles,type,name
0,5e0a7d50723412d564f87389b752f20b03f06367,CNC(=O)CCC(N)C(=O)OO,source,None
1,8420c4a15caf81754f2cb68c57e45e4fe98520b1,CC(=O)OC(C(=O)NCCC(=O)NCCSC(=O)CC(=O)C(=O)O)C(...,source,None
2,bca41fc9ccc4f70349c8e5ab4a1f5171f7a2f91b,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None
3,d1c9d47236eaba57e3694b9bb9e3c233ca04d89b,NC(=O)C1CC(N)C1O,source,None
4,6561ad1ddf87174e50bc16845d76388d58930061,CC(=O)N(CCC(=O)NCCSSCCNC(=O)CCNC(=O)C(O)C(C)(C...,source,None

In [4]:
df.loc[df['type'] == 'target']

,id,smiles,type,name
5458,6569ea8ebe9fdd8627adb76f7d942dbbbb83c56d,CC(C)(CO)C(=O)O,target,3hpa
5459,b4419ef13b0e2ce0034b0dfb2bda3aafe2afc298,CC(O)C(C)(C)C(=O)O,target,dmhb

In [6]:
df.loc[df['type'] == 'source']

,id,smiles,type,name
0,5e0a7d50723412d564f87389b752f20b03f06367,CNC(=O)CCC(N)C(=O)OO,source,None
1,8420c4a15caf81754f2cb68c57e45e4fe98520b1,CC(=O)OC(C(=O)NCCC(=O)NCCSC(=O)CC(=O)C(=O)O)C(...,source,None
2,bca41fc9ccc4f70349c8e5ab4a1f5171f7a2f91b,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None
3,d1c9d47236eaba57e3694b9bb9e3c233ca04d89b,NC(=O)C1CC(N)C1O,source,None
4,6561ad1ddf87174e50bc16845d76388d58930061,CC(=O)N(CCC(=O)NCCSSCCNC(=O)CCNC(=O)C(O)C(C)(C...,source,None
...,...,...,...,...
5453,23d5c42426784f931ef8aeba8137a06f71daa160,CSCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)O,source,None
5454,b75d7c1241893b08157280a21d21363bfaff1790,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(NC4OC(...,source,None
5455,fc855672ada66860b4b999d055619a8912e7b658,CC(=O)NC(=O)C(CC(N)C(=O)O)OO,source,None
5456,4a69405d520bee46d3d4a9af127e62771e10e32c,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None
5457,bf0338eba64bfe46347a57eedf98d3edcd63d736,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None