In [1]:
import pandas as pd

In [2]:
path = '/projects/b1039/spn1560/bottle/data/interim/expansions/3_steps_bottle_targets_25_to_None_rules_mechinferred_dt_04_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_False/compounds.parquet'

In [3]:
df = pd.read_parquet(path)
df.head()

,id,smiles,type,name
0,5e0a7d50723412d564f87389b752f20b03f06367,CNC(=O)CCC(N)C(=O)OO,source,None
1,8420c4a15caf81754f2cb68c57e45e4fe98520b1,CC(=O)OC(C(=O)NCCC(=O)NCCSC(=O)CC(=O)C(=O)O)C(...,source,None
2,bca41fc9ccc4f70349c8e5ab4a1f5171f7a2f91b,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None
3,d1c9d47236eaba57e3694b9bb9e3c233ca04d89b,NC(=O)C1CC(N)C1O,source,None
4,6561ad1ddf87174e50bc16845d76388d58930061,CC(=O)N(CCC(=O)NCCSSCCNC(=O)CCNC(=O)C(O)C(C)(C...,source,None

In [4]:
df.loc[df['type'] == 'target']

,id,smiles,type,name
5458,6569ea8ebe9fdd8627adb76f7d942dbbbb83c56d,CC(C)(CO)C(=O)O,target,3hpa
5459,b4419ef13b0e2ce0034b0dfb2bda3aafe2afc298,CC(O)C(C)(C)C(=O)O,target,dmhb

In [6]:
df.loc[df['type'] == 'source']

,id,smiles,type,name
0,5e0a7d50723412d564f87389b752f20b03f06367,CNC(=O)CCC(N)C(=O)OO,source,None
1,8420c4a15caf81754f2cb68c57e45e4fe98520b1,CC(=O)OC(C(=O)NCCC(=O)NCCSC(=O)CC(=O)C(=O)O)C(...,source,None
2,bca41fc9ccc4f70349c8e5ab4a1f5171f7a2f91b,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None
3,d1c9d47236eaba57e3694b9bb9e3c233ca04d89b,NC(=O)C1CC(N)C1O,source,None
4,6561ad1ddf87174e50bc16845d76388d58930061,CC(=O)N(CCC(=O)NCCSSCCNC(=O)CCNC(=O)C(O)C(C)(C...,source,None
...,...,...,...,...
5453,23d5c42426784f931ef8aeba8137a06f71daa160,CSCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)O,source,None
5454,b75d7c1241893b08157280a21d21363bfaff1790,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(NC4OC(...,source,None
5455,fc855672ada66860b4b999d055619a8912e7b658,CC(=O)NC(=O)C(CC(N)C(=O)O)OO,source,None
5456,4a69405d520bee46d3d4a9af127e62771e10e32c,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None
5457,bf0338eba64bfe46347a57eedf98d3edcd63d736,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,source,None

In [2]:
dir = '/home/stef/quest_data/bottle/data/interim/expansions/5_steps_ccm_aa_to_bottle_targets_25_combo_mechinferred_dt_13_and_mechinferred_dt_04_rules'
r = pd.read_parquet(f'{dir}/am_rxns.parquet')
r.head()

,smarts,am_smarts,rules,half_expansion,size
0,CC(=O)OS(=O)(=O)OCC(C)(C)C(=O)SCCNC(=O)CCNC(=O...,[CH3:1][C:2](=[O:3])[O:4][S:5](=[O:6])(=[O:7])...,"[mechinferred_dt_04:1373, mechinferred_dt_04:3...",retro,21
1,CC(C)(C(=O)O)C(=O)C(=O)SCCNC(=O)CCNC(=O)C(O)C(...,[CH3:54][C:53]([CH3:55])([C:56](=[O:57])[OH:58...,"[mechinferred_dt_04:1334, mechinferred_dt_04:6...",retro,16
2,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,[CH3:23][C:22]([CH3:24])([CH2:25][O:26][P:27](...,"[mechinferred_dt_04:1073, mechinferred_dt_04:4...",retro,8
3,CCC(C)C(NS(=O)(=O)O)C(=O)O.N.NC(=O)c1ccc[n+](C...,[CH3:1][CH2:2][CH:3]([CH3:4])[CH:5]([NH:6][S:7...,[mechinferred_dt_13:4314],forward,11
4,CC(C)(COP(=O)(O)OP(=O)(OCC1OC(n2cnc3c(N)ncnc32...,[CH3:70][C:69]([CH3:71])([CH2:68][O:67][P:64](...,"[mechinferred_dt_04:418, mechinferred_dt_04:2542]",retro,14

In [42]:
c = pd.read_parquet(f'{dir}/compounds.parquet')
c.head()

,id,smiles,type,name
0,fae11404b12230ded37cfd2511bf3dd98bdacd3c,O=C(O)CCC(=O)O,source,succinate
1,55e7ca03fb953e89747496916800481ee5f52b4a,O=C(O)C=CC(=O)O,source,fumarate
2,77d21e11cc906a4c9614c97db30147761a24e690,O=C(O)CC(O)C(=O)O,source,malate
3,20e696beb1325772afccb7eb1d2c187c70696753,O=C(O)CC(=O)C(=O)O,source,oxaloacetate
4,6cf6db1d70f43061de31deeb417214c6fd7ad005,O=C(O)CCC(=O)C(=O)O,source,ketoglutarate

In [43]:
c.loc[c['type'] == 'known']

,id,smiles,type,name
31,fdcd8d8828f3ad376fcece7b61607864e4d115a3,NC(CSSCC(N)C(=O)O)C(=O)O,known,L-cystine
32,2d8d382a3ebf42d363eba0aabe82f70add8ed85d,CC(N)C(=O)NC(C)C(=O)O,known,D-alanyl-D-alanine
33,045359bef2a4f5e667ab4afd2862bb2548b31dd0,O=C(O)C1NCCC1O,known,trans-3-hydroxy-L-proline
34,87d60fa4fabb6d8bbe8d8eab7454bcbb52f40391,O=C(O)CC(=O)O,known,malonate
35,3fd039a64a93138d45ed04ead31514e1d4774c97,O=C(O)C1CC(O)CN1,known,cis-4-hydroxy-D-proline
...,...,...,...,...
942,1753ce4adffebbd1a871cf1ff72b2243e8deea8e,Nc1ncnc2c1ncn2C1OC(COP(=O)(O)O)C(O)C1OP(=O)(O)O,known,"adenosine 2',5'-bisphosphate"
943,cbc229da926e08151b9a7858807239454859dffb,Nc1ncnc2c1ncn2C1CC(O)C(COP(=O)(O)O)O1,known,dAMP
944,4ffc869d9989b6de58444357579791b5855da410,Nc1ncnc2c1ncn2C1CC(O)C(COP(=O)(O)OP(=O)(O)OP(=...,known,dATP
945,56331dbce7c54cfd7c88b837c08ea34da0acde2b,CNc1ncnc2c1ncn2C1OC(COP(=O)(O)O)C(O)C1O,known,N(6)-methyl-AMP
946,9385c0000f897e2b610d4eda2170102d2428d898,CNc1ncnc2c1ncn2C1OC(COP(=O)(O)OP(=O)(O)OP(=O)(...,known,N(6)-methyl-ATP

In [33]:
c.loc[c['type'] == 'target']

                                          id              smiles    type  name
29  6569ea8ebe9fdd8627adb76f7d942dbbbb83c56d     CC(C)(CO)C(=O)O  target  3hpa
30  b4419ef13b0e2ce0034b0dfb2bda3aafe2afc298  CC(O)C(C)(C)C(=O)O  target  dmhb

In [34]:
kcs = pd.read_parquet(
    "../artifacts/known/known_compounds.parquet"
)
kcs.head()

,id,smiles,name,chebi_id,n_atoms
0,df58248c414f342c81e056b40bee12d17a08bf61,*,A,CHEBI:13193,1
1,bc2f74c22f98f7b6ffbc2f67453dbfa99bce9a32,**,RX,CHEBI:17792,2
2,e8ecd17bfc980925ff0b634bd13104c09dc4591f,*C,an alkane,CHEBI:18310,2
3,b219689f21c828e7f057ef453af1187baa98fbf3,*C#N,a nitrile,CHEBI:18379,3
4,94295b0379859ca57b86c85b0768526c711fe762,*C(*)(O)C(*)(*)O,an ethanediol,CHEBI:140594,8

In [35]:
kc_smi2name = dict(zip(kcs['smiles'], kcs['name'].to_list()))

In [36]:
c.loc[c['type'] == 'known', 'name'] = c.loc[c['type'] == 'known', 'smiles'].map(kc_smi2name)
c.head()

,id,smiles,type,name
0,fae11404b12230ded37cfd2511bf3dd98bdacd3c,O=C(O)CCC(=O)O,source,succinate
1,55e7ca03fb953e89747496916800481ee5f52b4a,O=C(O)C=CC(=O)O,source,fumarate
2,77d21e11cc906a4c9614c97db30147761a24e690,O=C(O)CC(O)C(=O)O,source,malate
3,20e696beb1325772afccb7eb1d2c187c70696753,O=C(O)CC(=O)C(=O)O,source,oxaloacetate
4,6cf6db1d70f43061de31deeb417214c6fd7ad005,O=C(O)CCC(=O)C(=O)O,source,ketoglutarate

In [37]:
c.loc[c['type'] == 'target']

                                          id              smiles    type  name
29  6569ea8ebe9fdd8627adb76f7d942dbbbb83c56d     CC(C)(CO)C(=O)O  target  3hpa
30  b4419ef13b0e2ce0034b0dfb2bda3aafe2afc298  CC(O)C(C)(C)C(=O)O  target  dmhb

In [38]:
import polars as pl

In [39]:
c = pl.from_pandas(c)
c.head()

shape: (5, 4)
┌─────────────────────────────────┬─────────────────────┬────────┬───────────────┐
│ id                              ┆ smiles              ┆ type   ┆ name          │
│ ---                             ┆ ---                 ┆ ---    ┆ ---           │
│ str                             ┆ str                 ┆ cat    ┆ str           │
╞═════════════════════════════════╪═════════════════════╪════════╪═══════════════╡
│ fae11404b12230ded37cfd2511bf3d… ┆ O=C(O)CCC(=O)O      ┆ source ┆ succinate     │
│ 55e7ca03fb953e8974749691680048… ┆ O=C(O)C=CC(=O)O     ┆ source ┆ fumarate      │
│ 77d21e11cc906a4c9614c97db30147… ┆ O=C(O)CC(O)C(=O)O   ┆ source ┆ malate        │
│ 20e696beb1325772afccb7eb1d2c18… ┆ O=C(O)CC(=O)C(=O)O  ┆ source ┆ oxaloacetate  │
│ 6cf6db1d70f43061de31deeb417214… ┆ O=C(O)CCC(=O)C(=O)O ┆ source ┆ ketoglutarate │
└─────────────────────────────────┴─────────────────────┴────────┴───────────────┘

In [40]:
dir

'/home/stef/quest_data/bottle/data/interim/expansions/5_steps_ccm_aa_to_bottle_targets_25_combo_mechinferred_dt_13_and_mechinferred_dt_04_rules'

In [ ]:
# c.write_parquet(dir + '/compounds.parquet')

In [45]:
gens = pl.DataFrame(
    {
        "half_expansion": ['forward', 'retro'],
        "generation": [2, 3],
    }
)
gens.write_csv(dir + '/generations.csv')

In [46]:
dir

'/home/stef/quest_data/bottle/data/interim/expansions/5_steps_ccm_aa_to_bottle_targets_25_combo_mechinferred_dt_13_and_mechinferred_dt_04_rules'