In [ ]:
import polars as pl
from rdkit import Chem
from itertools import chain

In [14]:
def extract_unique_smiles(df: pl.DataFrame, req_ids: list[str] = []) -> set[str]:
    if req_ids:
        df = df.filter(pl.col("id").is_in(req_ids))
    smarts = df['smarts'].to_list()
    mols = set(
        chain(
            *[
                side.split('.') for sma in smarts for side in sma.split('>>')
            ]
        )
    )
    return mols

In [15]:
fp = '../artifacts/coa_mutase_paths/250912_3hpa_paths.csv'
df = pl.read_csv(fp)

In [16]:
pmols = extract_unique_smiles(df)

In [18]:
krfp = "../artifacts/known/known_reactions.parquet"
krs = pl.read_parquet(krfp)
krs.head()

shape: (5, 5)
┌────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────┐
│ id                 ┆ smarts             ┆ enzymes           ┆ reverse           ┆ db_ids         │
│ ---                ┆ ---                ┆ ---               ┆ ---               ┆ ---            │
│ str                ┆ str                ┆ list[str]         ┆ str               ┆ list[str]      │
╞════════════════════╪════════════════════╪═══════════════════╪═══════════════════╪════════════════╡
│ e908a824c912d1e39c ┆ **.NC(CCC(=O)NC(CS ┆ ["P30109",        ┆ 3bbe8e6dca0da1c74 ┆ ["RHEA:16438"] │
│ 46de92d1f738…      ┆ )C(=O)NCC(=O…      ┆ "P57108", …       ┆ 5e7678c8efebe…    ┆                │
│                    ┆                    ┆ "P46436…          ┆                   ┆                │
│ d86d99a8143d3be8fc ┆ *.*.*.*.*.*.*.*.*. ┆ ["Q0UK48",        ┆ e99fb0b75e799eba7 ┆ ["RHEA:51350"] │
│ 861a5de5e625…      ┆ *.CC(C)(COP(…      ┆ "A0A0C6E0I7", …   ┆ 2aee21c1d04ee…    ┆                │
│                    ┆                    ┆ "A0…              ┆                   ┆                │
│ 2972b2db66715ba6f3 ┆ *.*.*.*.*.*.*.*.*N ┆ ["G0REX6",        ┆ 5a7fffef224c65b7c ┆ ["RHEA:64546"] │
│ d6aeaf07f31b…      ┆ C(COP(=O)(O)…      ┆ "P0DO30",         ┆ d431ddc668eb2…    ┆                │
│                    ┆                    ┆ "A0A482N9…        ┆                   ┆                │
│ 572e4a84a946af07c9 ┆ *.*.*.*.*.*.*.*.*O ┆ ["Q6M083",        ┆ c4c936d8d985a457a ┆ ["RHEA:64377"] │
│ ab6fd1c0347b…      ┆ P(=O)(O)OCC(…      ┆ "Q8U4J0", …       ┆ 128601b8d2769…    ┆                │
│                    ┆                    ┆ "C5A6E5…          ┆                   ┆                │
│ dfe7fc761de3c213bf ┆ *.*.*.*.*.*.*.*.CC ┆ ["Q6M083",        ┆ 2e026380a550baa6b ┆ ["RHEA:64369"] │
│ 2b18fae4f8a5…      ┆ (C)CCCC(C)CC…      ┆ "Q8U4J0", …       ┆ 343604e6f5500…    ┆                │
│                    ┆                    ┆ "C5A6E5…          ┆                   ┆                │
└────────────────────┴────────────────────┴───────────────────┴───────────────────┴────────────────┘

In [27]:
req_krids = [
    'd7eea5a1a938257639a2cbe5950fa3501a3fc821',
    'b4c25c288c30a8a0c671f4f171296e4f6785c7ba',
    'e28526a64f436e83d38207b68585369173b63e35',
    '4ef133095b54597cf464d3640d65a15cb75ba461',
    '7fa14c20e24cde2f3097739e7be1e2d30ddda6ef',

]

In [28]:
kmols = extract_unique_smiles(krs, req_krids)

In [29]:
with open("../artifacts/coa_mutase_paths/unique_smiles_for_chemdraw.txt", "w") as f:
    for smi in pmols | kmols:
        mol = Chem.MolFromSmiles(smi)
        if mol is not None:
            f.write(f"{smi}\n")

In [30]:
krs.filter(pl.col("id").is_in(req_krids)).select(["id", "enzymes", "db_ids"])

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────────┐
│ id                              ┆ enzymes                         ┆ db_ids         │
│ ---                             ┆ ---                             ┆ ---            │
│ str                             ┆ list[str]                       ┆ list[str]      │
╞═════════════════════════════════╪═════════════════════════════════╪════════════════╡
│ 4ef133095b54597cf464d3640d65a1… ┆ ["A9X6P9", "P76518"]            ┆ ["RHEA:37884"] │
│ d7eea5a1a938257639a2cbe5950fa3… ┆ ["Q8VCH6", "Q15392", … "Q60HC5… ┆ ["RHEA:36393"] │
│ b4c25c288c30a8a0c671f4f171296e… ┆ ["Q5KUG0", "A7IQE6", … "A7IQE5… ┆ ["RHEA:52621"] │
│ e28526a64f436e83d38207b6858536… ┆ ["O51628", "P13702"]            ┆ ["RHEA:14835"] │
│ 7fa14c20e24cde2f3097739e7be1e2… ┆ []                              ┆ ["RHEA:24761"] │
└─────────────────────────────────┴─────────────────────────────────┴────────────────┘