In [38]:
from src.post_processing import PathWrangler
import polars as pl
from pathlib import Path
from collections import defaultdict

In [39]:
study = "/home/stef/quest_data/bottle/data/processed/test"
known = "/home/stef/bottle/artifacts/known"
out_dir = "/home/stef/bottle/artifacts/coa_mutase_paths"

pw = PathWrangler(Path(study), Path(known))

In [6]:
tables = pw.get_paths()

In [7]:
paths = tables['paths']
krs = tables['known_reactions']
prs = tables['predicted_reactions']

pr2krs = dict(zip(prs['id'], prs['analogue_ids'].to_list()))
krs2enzymes = dict(zip(krs['id'], krs['enzymes'].to_list()))
prs2enzymes = defaultdict(list)
for p, ks in pr2krs.items():
    for k in ks:
        prs2enzymes[p] += krs2enzymes[k]

prs2smarts = dict(zip(prs['id'], prs['smarts'].to_list()))

paths = paths.select(
    pl.col("id"),
    pl.col("rxn_id"),
    (pl.col("generation") + 1).alias("step"),
    pl.col("starters").map_elements(lambda x : ";".join(x), return_dtype=pl.String),
    pl.col("targets").map_elements(lambda x : ";".join(x), return_dtype=pl.String),
    pl.col("rxn_id").replace_strict(prs2enzymes, default=[]).map_elements(lambda x : ";".join(x), return_dtype=pl.String).alias("enzymes"),
    pl.col("rxn_id").replace_strict(prs2smarts, default=None).alias("smarts")
)
paths

shape: (10, 7)
┌────────────────┬────────────────┬──────┬───────────────┬─────────┬───────────────┬───────────────┐
│ id             ┆ rxn_id         ┆ step ┆ starters      ┆ targets ┆ enzymes       ┆ smarts        │
│ ---            ┆ ---            ┆ ---  ┆ ---           ┆ ---     ┆ ---           ┆ ---           │
│ str            ┆ str            ┆ i32  ┆ str           ┆ str     ┆ str           ┆ str           │
╞════════════════╪════════════════╪══════╪═══════════════╪═════════╪═══════════════╪═══════════════╡
│ 0a24a1c33085a4 ┆ 5582845919356f ┆ 1    ┆ pyruvate      ┆ 3hpa    ┆ A9WGE2;A9WC35 ┆ CC(=O)SCCNC(= │
│ f1ea7f8e19ce06 ┆ 447668dd0ea464 ┆      ┆               ┆         ┆ ;Q8N0X4;S5N02 ┆ O)CCNC(=O)C(O │
│ c3…            ┆ 7f…            ┆      ┆               ┆         ┆ 0;Q8…         ┆ )C(C…         │
│ 0a24a1c33085a4 ┆ 8c16137b4045f0 ┆ 2    ┆ pyruvate      ┆ 3hpa    ┆ A9WC41;Q9JLZ3 ┆ CC(O)(CC(=O)S │
│ f1ea7f8e19ce06 ┆ 0069ba91d38a3b ┆      ┆               ┆         ┆ ;Q13825;Q1ZXF ┆ CCNC(=O)CCNC( │
│ c3…            ┆ 8b…            ┆      ┆               ┆         ┆ 1;F1…         ┆ =O)C…         │
│ 0a24a1c33085a4 ┆ 9c2c777c0fea42 ┆ 3    ┆ pyruvate      ┆ 3hpa    ┆ Q8VCH6;Q15392 ┆ CC(=CC(=O)SCC │
│ f1ea7f8e19ce06 ┆ 1a26efc2685752 ┆      ┆               ┆         ┆ ;Q5BQE6;Q60HC ┆ NC(=O)CCNC(=O │
│ c3…            ┆ 2f…            ┆      ┆               ┆         ┆ 5;Q3…         ┆ )C(O…         │
│ 0a24a1c33085a4 ┆ e86048734a2f69 ┆ 4    ┆ pyruvate      ┆ 3hpa    ┆ Q5KUG0;A7IQE6 ┆ CC(CC(=O)SCCN │
│ f1ea7f8e19ce06 ┆ f1257bd92b62dd ┆      ┆               ┆         ┆ ;Q1LRY0;A7IQE ┆ C(=O)CCNC(=O) │
│ c3…            ┆ b4…            ┆      ┆               ┆         ┆ 5             ┆ C(O)…         │
│ 0a24a1c33085a4 ┆ bd616dde067e27 ┆ 5    ┆ pyruvate      ┆ 3hpa    ┆ Q0P5J1;Q96K12 ┆ NC(=O)C1=CN(C │
│ f1ea7f8e19ce06 ┆ 86bec3a4ea2c6e ┆      ┆               ┆         ┆ ;Q7TNT2;Q0P5J ┆ 2OC(COP(=O)(O │
│ c3…            ┆ 17…            ┆      ┆               ┆         ┆ 1;Q9…         ┆ )OP(…         │
│ 9b13db2d9c8b6a ┆ 27450e93bf1eb2 ┆ 1    ┆ glutamic_acid ┆ 3hpa    ┆ Q24SG9;Q8RHY7 ┆ NC(CCC(=O)O)C │
│ 2b40034ef19b26 ┆ d982a541e9b347 ┆      ┆               ┆         ┆ ;P80078;Q73KI ┆ (=O)O>>CC(C(= │
│ 9b…            ┆ 24…            ┆      ┆               ┆         ┆ 2;Q5…         ┆ O)O)…         │
│ 9b13db2d9c8b6a ┆ 646032df080e79 ┆ 2    ┆ glutamic_acid ┆ 3hpa    ┆ A9X6P9;P76518 ┆ CC(C(=O)O)C(N │
│ 2b40034ef19b26 ┆ e8522e14d05d85 ┆      ┆               ┆         ┆ ;B0MC58;G2SYC ┆ )C(=O)O.CC(=O │
│ 9b…            ┆ 48…            ┆      ┆               ┆         ┆ 0;O0…         ┆ )SCC…         │
│ 9b13db2d9c8b6a ┆ 62277981d88329 ┆ 3    ┆ glutamic_acid ┆ 3hpa    ┆               ┆ NC(=O)C1=CN(C │
│ 2b40034ef19b26 ┆ 0bf5c0d4ed2585 ┆      ┆               ┆         ┆               ┆ 2OC(COP(=O)(O │
│ 9b…            ┆ 55…            ┆      ┆               ┆         ┆               ┆ )OP(…         │
│ 9b13db2d9c8b6a ┆ e86048734a2f69 ┆ 4    ┆ glutamic_acid ┆ 3hpa    ┆ Q5KUG0;A7IQE6 ┆ CC(CC(=O)SCCN │
│ 2b40034ef19b26 ┆ f1257bd92b62dd ┆      ┆               ┆         ┆ ;Q1LRY0;A7IQE ┆ C(=O)CCNC(=O) │
│ 9b…            ┆ b4…            ┆      ┆               ┆         ┆ 5             ┆ C(O)…         │
│ 9b13db2d9c8b6a ┆ bd616dde067e27 ┆ 5    ┆ glutamic_acid ┆ 3hpa    ┆ Q0P5J1;Q96K12 ┆ NC(=O)C1=CN(C │
│ 2b40034ef19b26 ┆ 86bec3a4ea2c6e ┆      ┆               ┆         ┆ ;Q7TNT2;Q0P5J ┆ 2OC(COP(=O)(O │
│ 9b…            ┆ 17…            ┆      ┆               ┆         ┆ 1;Q9…         ┆ )OP(…         │
└────────────────┴────────────────┴──────┴───────────────┴─────────┴───────────────┴───────────────┘

Direct look at parquet files

In [42]:
paths = pl.read_parquet(
    Path(study) / "paths.parquet"
)
paths.head()

shape: (5, 5)
┌────────────────────────┬────────────────────────┬───────────────────────┬───────────┬────────────┐
│ path_id                ┆ rxn_id                 ┆ main_pdt_id           ┆ rxn_type  ┆ generation │
│ ---                    ┆ ---                    ┆ ---                   ┆ ---       ┆ ---        │
│ str                    ┆ str                    ┆ str                   ┆ enum      ┆ i32        │
╞════════════════════════╪════════════════════════╪═══════════════════════╪═══════════╪════════════╡
│ 6a00d985f648ce51059730 ┆ 48960619c0f4a41ba25239 ┆ 31e1170961d93fe3e7baa ┆ predicted ┆ 0          │
│ c60da836…              ┆ 3d7e1b84…              ┆ e8ae55110…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ 3238d364a7911ad3440c41 ┆ cd431e4c6b05454079164 ┆ predicted ┆ 1          │
│ c60da836…              ┆ c05c944a…              ┆ 7925df16a…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ e00d2fd6f101dd3d9ac4cd ┆ 7adf4b7cf3272a4091055 ┆ predicted ┆ 2          │
│ c60da836…              ┆ a139cf0c…              ┆ af7ffa13e…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ bd616dde067e2786bec3a4 ┆ 6569ea8ebe9fdd8627adb ┆ predicted ┆ 4          │
│ c60da836…              ┆ ea2c6e17…              ┆ 76f7d942d…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ e86048734a2f69f1257bd9 ┆ 96d1eae18546609d08376 ┆ predicted ┆ 3          │
│ c60da836…              ┆ 2b62ddb4…              ┆ 61cc2b156…            ┆           ┆            │
└────────────────────────┴────────────────────────┴───────────────────────┴───────────┴────────────┘

In [43]:
path_stats = pl.read_parquet(
    Path(study) / "path_stats.parquet"
)
path_stats.head()

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ starters  ┆ targets   ┆ dg_opt    ┆ … ┆ mean_mean ┆ min_max_r ┆ min_mean_ ┆ feasibil │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _rxn_sim  ┆ xn_sim    ┆ rxn_sim   ┆ ity_frac │
│ str       ┆ list[str] ┆ list[str] ┆ list[f32] ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6a00d985f ┆ ["pyruvat ┆ ["3hpa"]  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 648ce5105 ┆ e", "meth ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9730c60da ┆ ionine"]  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 836…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
ps = path_stats.filter(
    pl.col("id") == '6a00d985f648ce51059730c60da836938782ae29'
).unique()

In [25]:
for elt in ps.group_by("id"):
    print(elt)

(('6a00d985f648ce51059730c60da836938782ae29',), shape: (2, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ starters  ┆ targets   ┆ dg_opt    ┆ … ┆ mean_mean ┆ min_max_r ┆ min_mean_ ┆ feasibil │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _rxn_sim  ┆ xn_sim    ┆ rxn_sim   ┆ ity_frac │
│ str       ┆ list[str] ┆ list[str] ┆ list[f32] ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6a00d985f ┆ ["methion ┆ ["3hpa"]  ┆ [-18.1495 ┆ … ┆ 0.641469  ┆ 0.454545  ┆ 0.409714  ┆ 1.0      │
│ 648ce5105 ┆ ine"]     ┆           ┆ 93, -18.1 ┆   ┆           ┆           ┆           ┆          │
│ 9730c60da ┆           ┆           ┆ 49593, …  ┆   ┆           ┆           ┆           ┆          │
│ 836…      ┆           ┆           ┆ -26…      ┆   ┆           ┆           ┆           ┆          │
│ 6a00d985f ┆ ["pyruvat ┆ ["3hpa"]  ┆ [-18.1495 ┆ … ┆ 0.641469  ┆ 0.454545  ┆ 0.409714  ┆ 1.0      │
│ 648ce5105 ┆ e"]       ┆           ┆ 93, -18.1 ┆   ┆           ┆           ┆           ┆          │
│ 9730c60da ┆           ┆           ┆ 49593, …  ┆   ┆           ┆           ┆           ┆          │
│ 836…      ┆           ┆           ┆ -26…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘)

In [ ]:
ps.group_by("id").agg(
    pl.col("starters").flatten().unique().alias("starters"),
    

)

shape: (1, 2)
┌─────────────────────────────────┬────────────────────────────┐
│ id                              ┆ starters                   │
│ ---                             ┆ ---                        │
│ str                             ┆ list[str]                  │
╞═════════════════════════════════╪════════════════════════════╡
│ 6a00d985f648ce51059730c60da836… ┆ ["methionine", "pyruvate"] │
└─────────────────────────────────┴────────────────────────────┘

In [28]:
ps.explode(['starters', 'targets', 'starter_ids', 'target_ids']).group_by('id').agg()

shape: (1, 1)
┌─────────────────────────────────┐
│ id                              │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ 6a00d985f648ce51059730c60da836… │
└─────────────────────────────────┘

In [22]:
paths.filter(
    pl.col("path_id") == '6a00d985f648ce51059730c60da836938782ae29'
).unique()

shape: (5, 5)
┌────────────────────────┬────────────────────────┬───────────────────────┬───────────┬────────────┐
│ path_id                ┆ rxn_id                 ┆ main_pdt_id           ┆ rxn_type  ┆ generation │
│ ---                    ┆ ---                    ┆ ---                   ┆ ---       ┆ ---        │
│ str                    ┆ str                    ┆ str                   ┆ enum      ┆ i32        │
╞════════════════════════╪════════════════════════╪═══════════════════════╪═══════════╪════════════╡
│ 6a00d985f648ce51059730 ┆ 3238d364a7911ad3440c41 ┆ cd431e4c6b05454079164 ┆ predicted ┆ 1          │
│ c60da836…              ┆ c05c944a…              ┆ 7925df16a…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ 48960619c0f4a41ba25239 ┆ 31e1170961d93fe3e7baa ┆ predicted ┆ 0          │
│ c60da836…              ┆ 3d7e1b84…              ┆ e8ae55110…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ bd616dde067e2786bec3a4 ┆ 6569ea8ebe9fdd8627adb ┆ predicted ┆ 4          │
│ c60da836…              ┆ ea2c6e17…              ┆ 76f7d942d…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ e86048734a2f69f1257bd9 ┆ 96d1eae18546609d08376 ┆ predicted ┆ 3          │
│ c60da836…              ┆ 2b62ddb4…              ┆ 61cc2b156…            ┆           ┆            │
│ 6a00d985f648ce51059730 ┆ e00d2fd6f101dd3d9ac4cd ┆ 7adf4b7cf3272a4091055 ┆ predicted ┆ 2          │
│ c60da836…              ┆ a139cf0c…              ┆ af7ffa13e…            ┆           ┆            │
└────────────────────────┴────────────────────────┴───────────────────────┴───────────┴────────────┘

In [7]:
whitelist = paths.filter(
    pl.col("path_id") == '6a00d985f648ce51059730c60da836938782ae29'
)["rxn_id"].unique().to_list()

In [8]:
am_rxns = pl.read_parquet(
    "/home/stef/quest_data/bottle/data/interim/expansions/5_steps_ccm_aa_to_bottle_targets_25_combo_mechinferred_dt_13_and_mechinferred_dt_04_rules/am_rxns.parquet"
)
am_rxns.head()

shape: (5, 5)
┌────────────────────────┬────────────────────────┬────────────────────────┬────────────────┬──────┐
│ smarts                 ┆ am_smarts              ┆ rules                  ┆ half_expansion ┆ size │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---            ┆ ---  │
│ str                    ┆ str                    ┆ list[str]              ┆ enum           ┆ i32  │
╞════════════════════════╪════════════════════════╪════════════════════════╪════════════════╪══════╡
│ CC(C)(C(=O)OP(=O)(O)O) ┆ [CH3:1][C:2]([CH3:3])( ┆ ["mechinferred_dt_04:1 ┆ retro          ┆ 7    │
│ C(O)C(OO…              ┆ [C:4](=[…              ┆ 759"]                  ┆                ┆      │
│ CC(=O)OP(=O)(O)OC1C(CO ┆ [CH3:28][C:29](=[O:30] ┆ ["mechinferred_dt_04:6 ┆ retro          ┆ 17   │
│ P(=O)(O)…              ┆ )[O:31][…              ┆ 200", "m…              ┆                ┆      │
│ NC(=O)C1=CN(C2OC(COP(= ┆ [NH2:92][C:93](=[O:94] ┆ ["mechinferred_dt_04:1 ┆ retro          ┆ 12   │
│ O)(O)OP(…              ┆ )[C:95]1…              ┆ 439"]                  ┆                ┆      │
│ CC(=O)Nc1ncnc2c1ncn2C1 ┆ [CH3:58][C:59](=[O:60] ┆ ["mechinferred_dt_04:1 ┆ retro          ┆ 5    │
│ OC(COP(=…              ┆ )[NH:61]…              ┆ 069"]                  ┆                ┆      │
│ O=c1ccn(C2OC(COP(=O)(O ┆ [O:1]=[c:2]1[cH:3][cH: ┆ ["mechinferred_dt_04:9 ┆ retro          ┆ 20   │
│ )OP(=O)(…              ┆ 4][n:5](…              ┆ 057"]                  ┆                ┆      │
└────────────────────────┴────────────────────────┴────────────────────────┴────────────────┴──────┘

In [32]:
pred_rxns = pl.read_parquet(
    Path(study) / "predicted_reactions.parquet"
)
pred_rxns.filter(
    pl.col("id").str.starts_with("4896061")
)["smarts"][0]

'CC(=O)C(=O)O.NC(C=O)CC(=O)O.CSCCC(N)C(=O)O>>NC(CO)CC(=O)O.C[S+](CCC(N)C(=O)O)CC(=O)C(=O)O'

In [ ]:

pred_rxns = pred_rxns.filter(
    pl.col("id").is_in(whitelist)
).select(
    ['smarts', 'am_smarts', 'rules']
).with_columns(
    pl.lit(8).alias("size")
)
pred_rxns.head()

In [15]:
def get_dir(rules: list[str]) -> str:
    rule_set = list(set(
        [r.split(":")[0] for r in rules]
    ))[0]
    if rule_set.startswith("mechinferred_dt_13"):
        return "forward"
    elif rule_set.startswith("mechinferred_dt_04"):
        return "retro"

In [16]:
pred_rxns = pred_rxns.with_columns(
    pl.col("rules").map_elements(get_dir, return_dtype=pl.String).alias("half_expansion")
)
pred_rxns.head()

shape: (5, 5)
┌────────────────────────┬────────────────────────┬────────────────────────┬──────┬────────────────┐
│ smarts                 ┆ am_smarts              ┆ rules                  ┆ size ┆ half_expansion │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---  ┆ ---            │
│ str                    ┆ str                    ┆ list[str]              ┆ i32  ┆ str            │
╞════════════════════════╪════════════════════════╪════════════════════════╪══════╪════════════════╡
│ CC(=O)C(=O)O.NC(C=O)CC ┆ [CH3:1][C:2](=[O:3])[C ┆ ["mechinferred_dt_13:6 ┆ 8    ┆ forward        │
│ (=O)O.CS…              ┆ :4](=[O:…              ┆ 81", "me…              ┆      ┆                │
│ NC(=O)C1=CN(C2OC(COP(= ┆ [NH2:105][C:106](=[O:1 ┆ ["mechinferred_dt_04:4 ┆ 8    ┆ retro          │
│ O)(O)OP(…              ┆ 07])[C:1…              ┆ 272", "m…              ┆      ┆                │
│ C[S+](CCC(N)C(=O)O)CC( ┆ [CH3:1][S+:2]([CH2:3][ ┆ ["mechinferred_dt_13:1 ┆ 8    ┆ forward        │
│ =O)C(=O)…              ┆ CH2:4][C…              ┆ 623", "m…              ┆      ┆                │
│ CC(CC(=O)SCCNC(=O)CCNC ┆ [CH3:3][CH:2]([CH2:1][ ┆ ["mechinferred_dt_04:3 ┆ 8    ┆ retro          │
│ (=O)C(O)…              ┆ C:7](=[O…              ┆ 939"]                  ┆      ┆                │
│ CC(CC(=O)O)C(=O)O.Nc1n ┆ [CH3:1][CH:2]([CH2:3][ ┆ ["mechinferred_dt_04:1 ┆ 8    ┆ retro          │
│ cnc2c1nc…              ┆ C:4](=[O…              ┆ 281", "m…              ┆      ┆                │
└────────────────────────┴────────────────────────┴────────────────────────┴──────┴────────────────┘

In [21]:
path_stats.unique()

shape: (2_700, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ starters  ┆ targets   ┆ dg_opt    ┆ … ┆ mean_mean ┆ min_max_r ┆ min_mean_ ┆ feasibil │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _rxn_sim  ┆ xn_sim    ┆ rxn_sim   ┆ ity_frac │
│ str       ┆ list[str] ┆ list[str] ┆ list[f32] ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ e609b2cc9 ┆ ["serine" ┆ ["3hpa"]  ┆ [170.9948 ┆ … ┆ 0.65158   ┆ 0.307793  ┆ 0.307793  ┆ 0.75     │
│ 7b0b40f3e ┆ ]         ┆           ┆ 58, 47.26 ┆   ┆           ┆           ┆           ┆          │
│ 6f9ac402f ┆           ┆           ┆ 7452, …   ┆   ┆           ┆           ┆           ┆          │
│ bdd…      ┆           ┆           ┆ -868…     ┆   ┆           ┆           ┆           ┆          │
│ 2d12cf0fe ┆ ["pyruvat ┆ ["3hpa"]  ┆ [-348.431 ┆ … ┆ 0.633617  ┆ 0.454545  ┆ 0.409714  ┆ 1.0      │
│ 313bcfa03 ┆ e"]       ┆           ┆ 061, -348 ┆   ┆           ┆           ┆           ┆          │
│ 1e42efcf8 ┆           ┆           ┆ .431061,  ┆   ┆           ┆           ┆           ┆          │
│ 33b…      ┆           ┆           ┆ … -…      ┆   ┆           ┆           ┆           ┆          │
│ 0bd539b8d ┆ ["tryptop ┆ ["3hpa"]  ┆ [-20.6434 ┆ … ┆ 0.700924  ┆ 0.681818  ┆ 0.537792  ┆ 1.0      │
│ c9cca7534 ┆ han"]     ┆           ┆ 88, -20.5 ┆   ┆           ┆           ┆           ┆          │
│ 5e2278396 ┆           ┆           ┆ 14862, …  ┆   ┆           ┆           ┆           ┆          │
│ 94c…      ┆           ┆           ┆ -26…      ┆   ┆           ┆           ┆           ┆          │
│ 1f0df8349 ┆ ["asparti ┆ ["3hpa"]  ┆ [-11.9560 ┆ … ┆ 0.705974  ┆ 0.636364  ┆ 0.609925  ┆ 0.6      │
│ b744537e1 ┆ c_acid"]  ┆           ┆ 59, -18.8 ┆   ┆           ┆           ┆           ┆          │
│ 0684002e1 ┆           ┆           ┆ 18769, …  ┆   ┆           ┆           ┆           ┆          │
│ 16f…      ┆           ┆           ┆ -22…      ┆   ┆           ┆           ┆           ┆          │
│ 05ab14379 ┆ ["oxaloac ┆ ["3hpa"]  ┆ [-7.62083 ┆ … ┆ 0.640281  ┆ 0.454545  ┆ 0.409714  ┆ 0.8      │
│ b6a8d1d62 ┆ etate"]   ┆           ┆ 2, -7.620 ┆   ┆           ┆           ┆           ┆          │
│ 53be6e326 ┆           ┆           ┆ 832, …    ┆   ┆           ┆           ┆           ┆          │
│ cc1…      ┆           ┆           ┆ -12.3…    ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 3f01e4e56 ┆ ["ketoglu ┆ ["3hpa"]  ┆ [-26.9051 ┆ … ┆ 0.738933  ┆ 0.681818  ┆ 0.627544  ┆ 1.0      │
│ 78e7e1ce0 ┆ tarate"]  ┆           ┆ 95, -22.4 ┆   ┆           ┆           ┆           ┆          │
│ f5f372b81 ┆           ┆           ┆ 92613, …  ┆   ┆           ┆           ┆           ┆          │
│ d1a…      ┆           ┆           ┆ -27…      ┆   ┆           ┆           ┆           ┆          │
│ 1cbcc4bc6 ┆ ["methion ┆ ["3hpa"]  ┆ [-780.289 ┆ … ┆ 0.616918  ┆ 0.454545  ┆ 0.409714  ┆ 1.0      │
│ 059cd23ad ┆ ine"]     ┆           ┆ 734, -780 ┆   ┆           ┆           ┆           ┆          │
│ 0e059a6ce ┆           ┆           ┆ .289734,  ┆   ┆           ┆           ┆           ┆          │
│ 68c…      ┆           ┆           ┆ … -…      ┆   ┆           ┆           ┆           ┆          │
│ 2e0ef32b9 ┆ ["malate" ┆ ["3hpa"]  ┆ [854.3689 ┆ … ┆ 0.703975  ┆ 0.681818  ┆ 0.555789  ┆ 1.0      │
│ 70982a520 ┆ ]         ┆           ┆ 58, 31.70 ┆   ┆           ┆           ┆           ┆          │
│ 10969c2b8 ┆           ┆           ┆ 7809, …   ┆   ┆           ┆           ┆           ┆          │
│ b73…      ┆           ┆           ┆ -7.9…     ┆   ┆           ┆           ┆           ┆          │
│ 1997bda66 ┆ ["methion ┆ ["3hpa"]  ┆ [-30.3059 ┆ … ┆ 0.618438  ┆ 0.454545  ┆ 0.409714  ┆ 1.0      │
│ 022abaf64 ┆ ine"]     ┆           ┆ 9, -30.30 ┆   ┆           ┆           ┆           ┆          │
│ e6c2d860d ┆           ┆           ┆ 599, …    ┆   ┆           ┆           ┆           ┆          │
│ 3cf…      ┆           ┆           ┆ -27.0…    ┆   ┆           ┆           ┆           ┆          │
│ da6da78b2 ┆ ["leucine ┆ ["3hpa"]  ┆ [-12.6309 ┆ … ┆ 0.763228  ┆ 0.57792   ┆ 0.450522  ┆ 0.6      │
│ e6bd612e7 ┆ "]        ┆           ┆ 86, -18.2 ┆   ┆           ┆           ┆           ┆          │
│ e8e6b7617 ┆           ┆           ┆ 76909, …  ┆   ┆           ┆           ┆           ┆          │
│ 1a1…      ┆           ┆           ┆ -13…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
pred_rxns.write_parquet(
    "/home/stef/quest_data/bottle/data/interim/expansions/test/am_rxns.parquet")

In [34]:
cpds = pl.read_parquet(
    "/home/stef/quest_data/bottle/data/interim/expansions/test/compounds.parquet"
)
cpds.head()

shape: (5, 4)
┌─────────────────────────────────┬─────────────────────┬────────┬───────────────┐
│ id                              ┆ smiles              ┆ type   ┆ name          │
│ ---                             ┆ ---                 ┆ ---    ┆ ---           │
│ str                             ┆ str                 ┆ enum   ┆ str           │
╞═════════════════════════════════╪═════════════════════╪════════╪═══════════════╡
│ fae11404b12230ded37cfd2511bf3d… ┆ O=C(O)CCC(=O)O      ┆ source ┆ succinate     │
│ 55e7ca03fb953e8974749691680048… ┆ O=C(O)C=CC(=O)O     ┆ source ┆ fumarate      │
│ 77d21e11cc906a4c9614c97db30147… ┆ O=C(O)CC(O)C(=O)O   ┆ source ┆ malate        │
│ 20e696beb1325772afccb7eb1d2c18… ┆ O=C(O)CC(=O)C(=O)O  ┆ source ┆ oxaloacetate  │
│ 6cf6db1d70f43061de31deeb417214… ┆ O=C(O)CCC(=O)C(=O)O ┆ source ┆ ketoglutarate │
└─────────────────────────────────┴─────────────────────┴────────┴───────────────┘

In [35]:
cpds.filter(
    pl.col("smiles") == "NC(C=O)CC(=O)O")

shape: (0, 4)
┌─────┬────────┬──────┬──────┐
│ id  ┆ smiles ┆ type ┆ name │
│ --- ┆ ---    ┆ ---  ┆ ---  │
│ str ┆ str    ┆ enum ┆ str  │
╞═════╪════════╪══════╪══════╡
└─────┴────────┴──────┴──────┘

Formatting a pull for collaborators

In [ ]:
enzymes = tables['enzymes']


enzymes.with_columns(
    pl.col("id").map_elements(lambda x : f"https://www.uniprot.org/uniprotkb/{x}/entry", return_dtype=pl.String).alias("link"),
)

In [ ]:
paths.write_csv(
    Path(out_dir) / "250912_3hpa_paths.csv",
    separator=','
)

enzymes.write_csv(
    Path(out_dir) / "250912_3hpa_enzymes.csv",
    separator=','
)

In [ ]:
from ergochemics.draw import draw_reaction
from IPython.display import SVG, display

In [ ]:
paths.filter(
    pl.col("id").str.starts_with("0a24a1c")
)

In [ ]:
for row in paths.filter(pl.col("id").str.starts_with("0a24a1c")).iter_rows(named=True):
    smarts = row['smarts']
    print(row['rxn_id'])
    display(SVG(draw_reaction(smarts)))

In [ ]:
prs.filter(
    pl.col("id") == "9c2c777c0fea421a26efc26857522fd2ccce1555"
)

In [ ]:
min_maps = pl.read_parquet(
    "/home/stef/bottle/artifacts/rxn_x_rule_mapping/mapped_known_reactions_x_rc_plus_0_rules.parquet"
)
min_maps.filter(
    pl.col("rxn_id") == "d7eea5a1a938257639a2cbe5950fa3501a3fc821"
)

In [ ]:
row['rxn_id']

In [ ]:
for row in min_maps.filter(pl.col("rule_id") == 515).iter_rows(named=True):
    smarts = row['smarts']
    print(row['rxn_id'])
    print(krs.filter(pl.col("id") == row['rxn_id'])['db_ids'])
    display(SVG(draw_reaction(smarts)))