In [54]:
from src.post_processing import PathWrangler
import polars as pl
from pathlib import Path
from collections import defaultdict

In [55]:
study = "/home/stef/quest_data/bottle/data/processed/lin_test"
known = "/home/stef/bottle/artifacts/known"
out_dir = "/home/stef/bottle/artifacts/coa_mutase_paths"

pw = PathWrangler(Path(study), Path(known))

In [56]:
tables = pw.get_paths()

In [75]:
paths = tables['paths']
krs = tables['known_reactions']
prs = tables['predicted_reactions']

pr2krs = dict(zip(prs['id'], prs['analogue_ids'].to_list()))
krs2enzymes = dict(zip(krs['id'], krs['enzymes'].to_list()))
prs2enzymes = defaultdict(list)
for p, ks in pr2krs.items():
    for k in ks:
        prs2enzymes[p] += krs2enzymes[k]

prs2smarts = dict(zip(prs['id'], prs['smarts'].to_list()))

paths = paths.select(
    pl.col("id"),
    pl.col("rxn_id"),
    (pl.col("generation") + 1).alias("step"),
    pl.col("starters").map_elements(lambda x : ";".join(x), return_dtype=pl.String),
    pl.col("targets").map_elements(lambda x : ";".join(x), return_dtype=pl.String),
    pl.col("rxn_id").replace_strict(prs2enzymes, default=[]).map_elements(lambda x : ";".join(x), return_dtype=pl.String).alias("enzymes"),
    pl.col("rxn_id").replace_strict(prs2smarts, default=None).alias("smarts")
)
paths

shape: (10, 7)
┌────────────────┬────────────────┬──────┬───────────────┬─────────┬───────────────┬───────────────┐
│ id             ┆ rxn_id         ┆ step ┆ starters      ┆ targets ┆ enzymes       ┆ smarts        │
│ ---            ┆ ---            ┆ ---  ┆ ---           ┆ ---     ┆ ---           ┆ ---           │
│ str            ┆ str            ┆ i32  ┆ str           ┆ str     ┆ str           ┆ str           │
╞════════════════╪════════════════╪══════╪═══════════════╪═════════╪═══════════════╪═══════════════╡
│ 0a24a1c33085a4 ┆ 5582845919356f ┆ 1    ┆ pyruvate      ┆ 3hpa    ┆ A9WGE2;A9WC35 ┆ CC(=O)SCCNC(= │
│ f1ea7f8e19ce06 ┆ 447668dd0ea464 ┆      ┆               ┆         ┆ ;Q8N0X4;S5N02 ┆ O)CCNC(=O)C(O │
│ c3…            ┆ 7f…            ┆      ┆               ┆         ┆ 0;Q8…         ┆ )C(C…         │
│ 0a24a1c33085a4 ┆ 8c16137b4045f0 ┆ 2    ┆ pyruvate      ┆ 3hpa    ┆ A9WC41;Q9JLZ3 ┆ CC(O)(CC(=O)S │
│ f1ea7f8e19ce06 ┆ 0069ba91d38a3b ┆      ┆               ┆         ┆ ;Q13825;Q1ZXF ┆ CCNC(=O)CCNC( │
│ c3…            ┆ 8b…            ┆      ┆               ┆         ┆ 1;F1…         ┆ =O)C…         │
│ 0a24a1c33085a4 ┆ 9c2c777c0fea42 ┆ 3    ┆ pyruvate      ┆ 3hpa    ┆ Q8VCH6;Q15392 ┆ CC(=CC(=O)SCC │
│ f1ea7f8e19ce06 ┆ 1a26efc2685752 ┆      ┆               ┆         ┆ ;Q5BQE6;Q60HC ┆ NC(=O)CCNC(=O │
│ c3…            ┆ 2f…            ┆      ┆               ┆         ┆ 5;Q3…         ┆ )C(O…         │
│ 0a24a1c33085a4 ┆ e86048734a2f69 ┆ 4    ┆ pyruvate      ┆ 3hpa    ┆ Q5KUG0;A7IQE6 ┆ CC(CC(=O)SCCN │
│ f1ea7f8e19ce06 ┆ f1257bd92b62dd ┆      ┆               ┆         ┆ ;Q1LRY0;A7IQE ┆ C(=O)CCNC(=O) │
│ c3…            ┆ b4…            ┆      ┆               ┆         ┆ 5             ┆ C(O)…         │
│ 0a24a1c33085a4 ┆ bd616dde067e27 ┆ 5    ┆ pyruvate      ┆ 3hpa    ┆ Q0P5J1;Q96K12 ┆ NC(=O)C1=CN(C │
│ f1ea7f8e19ce06 ┆ 86bec3a4ea2c6e ┆      ┆               ┆         ┆ ;Q7TNT2;Q0P5J ┆ 2OC(COP(=O)(O │
│ c3…            ┆ 17…            ┆      ┆               ┆         ┆ 1;Q9…         ┆ )OP(…         │
│ 9b13db2d9c8b6a ┆ 27450e93bf1eb2 ┆ 1    ┆ glutamic_acid ┆ 3hpa    ┆ Q24SG9;Q8RHY7 ┆ NC(CCC(=O)O)C │
│ 2b40034ef19b26 ┆ d982a541e9b347 ┆      ┆               ┆         ┆ ;P80078;Q73KI ┆ (=O)O>>CC(C(= │
│ 9b…            ┆ 24…            ┆      ┆               ┆         ┆ 2;Q5…         ┆ O)O)…         │
│ 9b13db2d9c8b6a ┆ 646032df080e79 ┆ 2    ┆ glutamic_acid ┆ 3hpa    ┆ A9X6P9;P76518 ┆ CC(C(=O)O)C(N │
│ 2b40034ef19b26 ┆ e8522e14d05d85 ┆      ┆               ┆         ┆ ;B0MC58;G2SYC ┆ )C(=O)O.CC(=O │
│ 9b…            ┆ 48…            ┆      ┆               ┆         ┆ 0;O0…         ┆ )SCC…         │
│ 9b13db2d9c8b6a ┆ 62277981d88329 ┆ 3    ┆ glutamic_acid ┆ 3hpa    ┆               ┆ NC(=O)C1=CN(C │
│ 2b40034ef19b26 ┆ 0bf5c0d4ed2585 ┆      ┆               ┆         ┆               ┆ 2OC(COP(=O)(O │
│ 9b…            ┆ 55…            ┆      ┆               ┆         ┆               ┆ )OP(…         │
│ 9b13db2d9c8b6a ┆ e86048734a2f69 ┆ 4    ┆ glutamic_acid ┆ 3hpa    ┆ Q5KUG0;A7IQE6 ┆ CC(CC(=O)SCCN │
│ 2b40034ef19b26 ┆ f1257bd92b62dd ┆      ┆               ┆         ┆ ;Q1LRY0;A7IQE ┆ C(=O)CCNC(=O) │
│ 9b…            ┆ b4…            ┆      ┆               ┆         ┆ 5             ┆ C(O)…         │
│ 9b13db2d9c8b6a ┆ bd616dde067e27 ┆ 5    ┆ glutamic_acid ┆ 3hpa    ┆ Q0P5J1;Q96K12 ┆ NC(=O)C1=CN(C │
│ 2b40034ef19b26 ┆ 86bec3a4ea2c6e ┆      ┆               ┆         ┆ ;Q7TNT2;Q0P5J ┆ 2OC(COP(=O)(O │
│ 9b…            ┆ 17…            ┆      ┆               ┆         ┆ 1;Q9…         ┆ )OP(…         │
└────────────────┴────────────────┴──────┴───────────────┴─────────┴───────────────┴───────────────┘

In [62]:
enzymes = tables['enzymes']


enzymes.with_columns(
    pl.col("id").map_elements(lambda x : f"https://www.uniprot.org/uniprotkb/{x}/entry", return_dtype=pl.String).alias("link"),
)

shape: (261, 9)
┌────────────┬────────────┬───────────┬──────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ id         ┆ sequence   ┆ existence ┆ reviewed ┆ … ┆ organism  ┆ name      ┆ subunit ┆ link      │
│ ---        ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---     ┆ ---       │
│ str        ┆ str        ┆ enum      ┆ enum     ┆   ┆ str       ┆ str       ┆ bool    ┆ str       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ A0A0A1C3I2 ┆ MDVRRRLPPK ┆ Evidence  ┆ reviewed ┆ … ┆ Panax     ┆ 3-hydroxy ┆ false   ┆ https://w │
│            ┆ LRRPLPITES ┆ at transc ┆          ┆   ┆ ginseng   ┆ -3-methyl ┆         ┆ ww.unipro │
│            ┆ SHHHRKTPFP ┆ ript      ┆          ┆   ┆ (Korean   ┆ glutaryl  ┆         ┆ t.org/uni │
│            ┆ …          ┆ level     ┆          ┆   ┆ ginseng)  ┆ coe…      ┆         ┆ pro…      │
│ A0A0A1C930 ┆ MDVRRRPVKS ┆ Evidence  ┆ reviewed ┆ … ┆ Panax     ┆ 3-hydroxy ┆ false   ┆ https://w │
│            ┆ LSSAKTATAG ┆ at transc ┆          ┆   ┆ ginseng   ┆ -3-methyl ┆         ┆ ww.unipro │
│            ┆ EPPKSQQQHP ┆ ript      ┆          ┆   ┆ (Korean   ┆ glutaryl  ┆         ┆ t.org/uni │
│            ┆ …          ┆ level     ┆          ┆   ┆ ginseng)  ┆ coe…      ┆         ┆ pro…      │
│ A7Z064     ┆ MLSRLFRMHG ┆ Evidence  ┆ reviewed ┆ … ┆ Bos       ┆ 3-hydroxy ┆ false   ┆ https://w │
│            ┆ LFVASHPWEV ┆ at transc ┆          ┆   ┆ taurus    ┆ -3-methyl ┆         ┆ ww.unipro │
│            ┆ IVGTVTLTIC ┆ ript      ┆          ┆   ┆ (Bovine)  ┆ glutaryl- ┆         ┆ t.org/uni │
│            ┆ …          ┆ level     ┆          ┆   ┆           ┆ coe…      ┆         ┆ pro…      │
│ A9WGE2     ┆ MEAVTIVDVA ┆ Evidence  ┆ reviewed ┆ … ┆ Chlorofle ┆ (R)-citra ┆ false   ┆ https://w │
│            ┆ PRDGLQNEPD ┆ at        ┆          ┆   ┆ xus auran ┆ malyl-CoA ┆         ┆ ww.unipro │
│            ┆ VLEPATRVEL ┆ protein   ┆          ┆   ┆ tiacus    ┆ lyase (EC ┆         ┆ t.org/uni │
│            ┆ …          ┆ level     ┆          ┆   ┆ (stra…    ┆ 4…        ┆         ┆ pro…      │
│ B2GV06     ┆ MAALKLLSSG ┆ Evidence  ┆ reviewed ┆ … ┆ Rattus    ┆ Succinyl- ┆ false   ┆ https://w │
│            ┆ LRLCASARNS ┆ at        ┆          ┆   ┆ norvegicu ┆ CoA:3-ket ┆         ┆ ww.unipro │
│            ┆ RGALHKGCAC ┆ protein   ┆          ┆   ┆ s (Rat)   ┆ oacid     ┆         ┆ t.org/uni │
│            ┆ …          ┆ level     ┆          ┆   ┆           ┆ coenzy…   ┆         ┆ pro…      │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ Q5V468     ┆ MGALDDLRVL ┆ Evidence  ┆ reviewed ┆ … ┆ Haloarcul ┆ Succinyl- ┆ false   ┆ https://w │
│            ┆ DLTQVLAGPY ┆ at        ┆          ┆   ┆ a marismo ┆ CoA:mesac ┆         ┆ ww.unipro │
│            ┆ CTMLLADMGA ┆ protein   ┆          ┆   ┆ rtui      ┆ onate     ┆         ┆ t.org/uni │
│            ┆ …          ┆ level     ┆          ┆   ┆ (strain…  ┆ CoA-tr…   ┆         ┆ pro…      │
│ Q9V1R3     ┆ MNVEDIIEKV ┆ Inferred  ┆ reviewed ┆ … ┆ Pyrococcu ┆ 3-hydroxy ┆ false   ┆ https://w │
│            ┆ ANGEIKLHQV ┆ from      ┆          ┆   ┆ s abyssi  ┆ -3-methyl ┆         ┆ ww.unipro │
│            ┆ EKYVNGDKRL ┆ homology  ┆          ┆   ┆ (strain   ┆ glutaryl- ┆         ┆ t.org/uni │
│            ┆ …          ┆           ┆          ┆   ┆ GE5 …     ┆ coe…      ┆         ┆ pro…      │
│ Q9YAS4     ┆ MGSSSGQKPR ┆ Inferred  ┆ reviewed ┆ … ┆ Aeropyrum ┆ 3-hydroxy ┆ false   ┆ https://w │
│            ┆ RLEDLVDKLA ┆ from      ┆          ┆   ┆ pernix    ┆ -3-methyl ┆         ┆ ww.unipro │
│            ┆ SGSLSHSRLE ┆ homology  ┆          ┆   ┆ (strain   ┆ glutaryl- ┆         ┆ t.org/uni │
│            ┆ …          ┆           ┆          ┆   ┆ ATCC …    ┆ coe…      ┆         ┆ pro…      │
│ Q9ZLE3     ┆ MNKVITDLDK ┆ Inferred  ┆ reviewed ┆ … ┆ Helicobac ┆ Succinyl- ┆ true    ┆ https://w │
│            ┆ ALSGLKDGDT ┆ from      ┆          ┆   ┆ ter       ┆ CoA:3-ket ┆         ┆ ww.unipro │
│            ┆ ILVGGFGLCG ┆ homology  ┆          ┆   ┆ pylori    ┆ oacid     ┆         ┆ t.org/uni │
│            ┆ …          ┆           ┆          ┆   ┆ (strain   ┆ coenzy…   ┆         ┆ pro…      │
│            ┆            ┆           ┆          ┆   ┆ J9…       ┆           ┆         ┆           │
│ Q9ZLE4     ┆ MREAIIKRAA ┆ Inferred  ┆ reviewed ┆ … ┆ Helicobac ┆ Succinyl- ┆ true    ┆ https://w │
│            ┆ KELKEGMYVN ┆ from      ┆          ┆   ┆ ter       ┆ CoA:3-ket ┆         ┆ ww.unipro │
│            ┆ LGIGLPTLVA ┆ homology  ┆          ┆   ┆ pylori    ┆ oacid     ┆         ┆ t.org/uni │
│            ┆ …          ┆           ┆          ┆   ┆ (strain   ┆ coenzy…   ┆         ┆ pro…      │
│            ┆            ┆           ┆          ┆   ┆ J9…       ┆           ┆         ┆           │
└────────────┴────────────┴───────────┴──────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [76]:
paths.write_csv(
    Path(out_dir) / "250912_3hpa_paths.csv",
    separator=','
)

enzymes.write_csv(
    Path(out_dir) / "250912_3hpa_enzymes.csv",
    separator=','
)